/*
 * Generated by dtrace(1M).
 */

#ifndef	_JAVASCRIPT_TRACE_H
#define	_JAVASCRIPT_TRACE_H

#include <unistd.h>

#ifdef	__cplusplus
extern "C" {
#endif

#define JAVASCRIPT_STABILITY "___dtrace_stability$javascript$v1$1_1_0_1_1_0_1_1_0_1_1_0_1_1_0"

#define JAVASCRIPT_TYPEDEFS "___dtrace_typedefs$javascript$v2"

#define	JAVASCRIPT_EXECUTE_DONE(arg0, arg1) \
do { \
	__asm__ volatile(".reference " JAVASCRIPT_TYPEDEFS); \
	__dtrace_probe$javascript$execute__done$v1$63686172202a$696e74(arg0, arg1); \
	__asm__ volatile(".reference " JAVASCRIPT_STABILITY); \
} while (0)
#define	JAVASCRIPT_EXECUTE_DONE_ENABLED() \
	__dtrace_isenabled$javascript$execute__done$v1()
#define	JAVASCRIPT_EXECUTE_START(arg0, arg1) \
do { \
	__asm__ volatile(".reference " JAVASCRIPT_TYPEDEFS); \
	__dtrace_probe$javascript$execute__start$v1$63686172202a$696e74(arg0, arg1); \
	__asm__ volatile(".reference " JAVASCRIPT_STABILITY); \
} while (0)
#define	JAVASCRIPT_EXECUTE_START_ENABLED() \
	__dtrace_isenabled$javascript$execute__start$v1()
#define	JAVASCRIPT_FUNCTION_ARGS(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) \
do { \
	__asm__ volatile(".reference " JAVASCRIPT_TYPEDEFS); \
	__dtrace_probe$javascript$function__args$v1$63686172202a$63686172202a$63686172202a$696e74$766f6964202a$766f6964202a$766f6964202a$766f6964202a$766f6964202a$766f6964202a(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9); \
	__asm__ volatile(".reference " JAVASCRIPT_STABILITY); \
} while (0)
#define	JAVASCRIPT_FUNCTION_ARGS_ENABLED() \
	__dtrace_isenabled$javascript$function__args$v1()
#define	JAVASCRIPT_FUNCTION_ENTRY(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " JAVASCRIPT_TYPEDEFS); \
	__dtrace_probe$javascript$function__entry$v1$63686172202a$63686172202a$63686172202a(arg0, arg1, arg2); \
	__asm__ volatile(".reference " JAVASCRIPT_STABILITY); \
} while (0)
#define	JAVASCRIPT_FUNCTION_ENTRY_ENABLED() \
	__dtrace_isenabled$javascript$function__entry$v1()
#define	JAVASCRIPT_FUNCTION_INFO(arg0, arg1, arg2, arg3, arg4, arg5) \
do { \
	__asm__ volatile(".reference " JAVASCRIPT_TYPEDEFS); \
	__dtrace_probe$javascript$function__info$v1$63686172202a$63686172202a$63686172202a$696e74$63686172202a$696e74(arg0, arg1, arg2, arg3, arg4, arg5); \
	__asm__ volatile(".reference " JAVASCRIPT_STABILITY); \
} while (0)
#define	JAVASCRIPT_FUNCTION_INFO_ENABLED() \
	__dtrace_isenabled$javascript$function__info$v1()
#define	JAVASCRIPT_FUNCTION_RETURN(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " JAVASCRIPT_TYPEDEFS); \
	__dtrace_probe$javascript$function__return$v1$63686172202a$63686172202a$63686172202a(arg0, arg1, arg2); \
	__asm__ volatile(".reference " JAVASCRIPT_STABILITY); \
} while (0)
#define	JAVASCRIPT_FUNCTION_RETURN_ENABLED() \
	__dtrace_isenabled$javascript$function__return$v1()
#define	JAVASCRIPT_FUNCTION_RVAL(arg0, arg1, arg2, arg3, arg4, arg5) \
do { \
	__asm__ volatile(".reference " JAVASCRIPT_TYPEDEFS); \
	__dtrace_probe$javascript$function__rval$v1$63686172202a$63686172202a$63686172202a$696e74$766f6964202a$766f6964202a(arg0, arg1, arg2, arg3, arg4, arg5); \
	__asm__ volatile(".reference " JAVASCRIPT_STABILITY); \
} while (0)
#define	JAVASCRIPT_FUNCTION_RVAL_ENABLED() \
	__dtrace_isenabled$javascript$function__rval$v1()
#define	JAVASCRIPT_OBJECT_CREATE(arg0, arg1, arg2, arg3) \
do { \
	__asm__ volatile(".reference " JAVASCRIPT_TYPEDEFS); \
	__dtrace_probe$javascript$object__create$v1$63686172202a$63686172202a$756e7369676e6564206c6f6e67$696e74(arg0, arg1, arg2, arg3); \
	__asm__ volatile(".reference " JAVASCRIPT_STABILITY); \
} while (0)
#define	JAVASCRIPT_OBJECT_CREATE_ENABLED() \
	__dtrace_isenabled$javascript$object__create$v1()
#define	JAVASCRIPT_OBJECT_CREATE_DONE(arg0, arg1) \
do { \
	__asm__ volatile(".reference " JAVASCRIPT_TYPEDEFS); \
	__dtrace_probe$javascript$object__create__done$v1$63686172202a$63686172202a(arg0, arg1); \
	__asm__ volatile(".reference " JAVASCRIPT_STABILITY); \
} while (0)
#define	JAVASCRIPT_OBJECT_CREATE_DONE_ENABLED() \
	__dtrace_isenabled$javascript$object__create__done$v1()
#define	JAVASCRIPT_OBJECT_CREATE_START(arg0, arg1) \
do { \
	__asm__ volatile(".reference " JAVASCRIPT_TYPEDEFS); \
	__dtrace_probe$javascript$object__create__start$v1$63686172202a$63686172202a(arg0, arg1); \
	__asm__ volatile(".reference " JAVASCRIPT_STABILITY); \
} while (0)
#define	JAVASCRIPT_OBJECT_CREATE_START_ENABLED() \
	__dtrace_isenabled$javascript$object__create__start$v1()
#define	JAVASCRIPT_OBJECT_FINALIZE(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " JAVASCRIPT_TYPEDEFS); \
	__dtrace_probe$javascript$object__finalize$v1$63686172202a$63686172202a$756e7369676e6564206c6f6e67(arg0, arg1, arg2); \
	__asm__ volatile(".reference " JAVASCRIPT_STABILITY); \
} while (0)
#define	JAVASCRIPT_OBJECT_FINALIZE_ENABLED() \
	__dtrace_isenabled$javascript$object__finalize$v1()


extern void __dtrace_probe$javascript$execute__done$v1$63686172202a$696e74(char *, int);
extern int __dtrace_isenabled$javascript$execute__done$v1(void);
extern void __dtrace_probe$javascript$execute__start$v1$63686172202a$696e74(char *, int);
extern int __dtrace_isenabled$javascript$execute__start$v1(void);
extern void __dtrace_probe$javascript$function__args$v1$63686172202a$63686172202a$63686172202a$696e74$766f6964202a$766f6964202a$766f6964202a$766f6964202a$766f6964202a$766f6964202a(char *, char *, char *, int, void *, void *, void *, void *, void *, void *);
extern int __dtrace_isenabled$javascript$function__args$v1(void);
extern void __dtrace_probe$javascript$function__entry$v1$63686172202a$63686172202a$63686172202a(char *, char *, char *);
extern int __dtrace_isenabled$javascript$function__entry$v1(void);
extern void __dtrace_probe$javascript$function__info$v1$63686172202a$63686172202a$63686172202a$696e74$63686172202a$696e74(char *, char *, char *, int, char *, int);
extern int __dtrace_isenabled$javascript$function__info$v1(void);
extern void __dtrace_probe$javascript$function__return$v1$63686172202a$63686172202a$63686172202a(char *, char *, char *);
extern int __dtrace_isenabled$javascript$function__return$v1(void);
extern void __dtrace_probe$javascript$function__rval$v1$63686172202a$63686172202a$63686172202a$696e74$766f6964202a$766f6964202a(char *, char *, char *, int, void *, void *);
extern int __dtrace_isenabled$javascript$function__rval$v1(void);
extern void __dtrace_probe$javascript$object__create$v1$63686172202a$63686172202a$756e7369676e6564206c6f6e67$696e74(char *, char *, unsigned long, int);
extern int __dtrace_isenabled$javascript$object__create$v1(void);
extern void __dtrace_probe$javascript$object__create__done$v1$63686172202a$63686172202a(char *, char *);
extern int __dtrace_isenabled$javascript$object__create__done$v1(void);
extern void __dtrace_probe$javascript$object__create__start$v1$63686172202a$63686172202a(char *, char *);
extern int __dtrace_isenabled$javascript$object__create__start$v1(void);
extern void __dtrace_probe$javascript$object__finalize$v1$63686172202a$63686172202a$756e7369676e6564206c6f6e67(char *, char *, unsigned long);
extern int __dtrace_isenabled$javascript$object__finalize$v1(void);

#ifdef	__cplusplus
}
#endif

#endif	/* _JAVASCRIPT_TRACE_H */
