/*
 *  Warning: Do not edit this file.  It was automatically
 *  generated by 'make_tables' on Mon Sep 13 15:06:40 2010.
 */

#ifndef __ERL_BIF_TABLE_H__
#define __ERL_BIF_TABLE_H__
typedef void *BifFunction;

typedef struct bif_entry {
    Eterm module;
    Eterm name;
    int arity;
    BifFunction f;
    BifFunction traced;
} BifEntry;

extern BifEntry bif_table[];
extern Export* bif_export[];
extern unsigned char erts_bif_trace_flags[];

#define BIF_SIZE 634

#define BIF_abs_1 0
#define BIF_ebif_abs_1 1
#define BIF_adler32_1 2
#define BIF_ebif_adler32_1 3
#define BIF_adler32_2 4
#define BIF_ebif_adler32_2 5
#define BIF_adler32_combine_3 6
#define BIF_ebif_adler32_combine_3 7
#define BIF_apply_3 8
#define BIF_ebif_apply_3 9
#define BIF_atom_to_list_1 10
#define BIF_ebif_atom_to_string_1 11
#define BIF_binary_to_list_1 12
#define BIF_ebif_binary_to_list_1 13
#define BIF_binary_to_list_3 14
#define BIF_ebif_binary_to_list_3 15
#define BIF_binary_to_term_1 16
#define BIF_ebif_binary_to_term_1 17
#define BIF_check_process_code_2 18
#define BIF_ebif_check_process_code_2 19
#define BIF_crc32_1 20
#define BIF_ebif_crc32_1 21
#define BIF_crc32_2 22
#define BIF_ebif_crc32_2 23
#define BIF_crc32_combine_3 24
#define BIF_ebif_crc32_combine_3 25
#define BIF_date_0 26
#define BIF_ebif_date_0 27
#define BIF_delete_module_1 28
#define BIF_ebif_delete_module_1 29
#define BIF_display_1 30
#define BIF_ebif_display_1 31
#define BIF_display_string_1 32
#define BIF_ebif_display_string_1 33
#define BIF_display_nl_0 34
#define BIF_ebif_display_nl_0 35
#define BIF_element_2 36
#define BIF_ebif_element_2 37
#define BIF_erase_0 38
#define BIF_ebif_erase_0 39
#define BIF_erase_1 40
#define BIF_ebif_erase_1 41
#define BIF_exit_1 42
#define BIF_ebif_exit_1 43
#define BIF_exit_2 44
#define BIF_ebif_signal_2 45
#define BIF_external_size_1 46
#define BIF_ebif_external_size_1 47
#define BIF_float_1 48
#define BIF_ebif_to_float_1 49
#define BIF_float_to_list_1 50
#define BIF_ebif_float_to_string_1 51
#define BIF_fun_info_2 52
#define BIF_ebif_fun_info_2 53
#define BIF_garbage_collect_0 54
#define BIF_ebif_garbage_collect_0 55
#define BIF_garbage_collect_1 56
#define BIF_ebif_garbage_collect_1 57
#define BIF_garbage_collect_message_area_0 58
#define BIF_ebif_garbage_collect_message_area_0 59
#define BIF_get_0 60
#define BIF_ebif_get_0 61
#define BIF_get_1 62
#define BIF_ebif_get_1 63
#define BIF_get_keys_1 64
#define BIF_ebif_get_keys_1 65
#define BIF_group_leader_0 66
#define BIF_ebif_group_leader_0 67
#define BIF_group_leader_2 68
#define BIF_ebif_group_leader_2 69
#define BIF_halt_0 70
#define BIF_ebif_halt_0 71
#define BIF_halt_1 72
#define BIF_ebif_halt_1 73
#define BIF_phash_2 74
#define BIF_phash2_1 75
#define BIF_phash2_2 76
#define BIF_ebif_phash2_1 77
#define BIF_ebif_phash2_2 78
#define BIF_hd_1 79
#define BIF_ebif_hd_1 80
#define BIF_integer_to_list_1 81
#define BIF_ebif_integer_to_string_1 82
#define BIF_is_alive_0 83
#define BIF_ebif_is_alive_0 84
#define BIF_length_1 85
#define BIF_ebif_length_1 86
#define BIF_link_1 87
#define BIF_ebif_link_1 88
#define BIF_list_to_atom_1 89
#define BIF_ebif_string_to_atom_1 90
#define BIF_list_to_binary_1 91
#define BIF_ebif_list_to_binary_1 92
#define BIF_list_to_float_1 93
#define BIF_ebif_string_to_float_1 94
#define BIF_list_to_integer_1 95
#define BIF_ebif_string_to_integer_1 96
#define BIF_list_to_pid_1 97
#define BIF_ebif_string_to_pid_1 98
#define BIF_list_to_tuple_1 99
#define BIF_ebif_list_to_tuple_1 100
#define BIF_load_module_2 101
#define BIF_ebif_load_module_2 102
#define BIF_loaded_0 103
#define BIF_ebif_loaded_0 104
#define BIF_localtime_0 105
#define BIF_ebif_localtime_0 106
#define BIF_localtime_to_universaltime_2 107
#define BIF_ebif_localtime_to_universaltime_2 108
#define BIF_make_ref_0 109
#define BIF_ebif_make_ref_0 110
#define BIF_md5_1 111
#define BIF_ebif_md5_1 112
#define BIF_md5_init_0 113
#define BIF_ebif_md5_init_0 114
#define BIF_md5_update_2 115
#define BIF_ebif_md5_update_2 116
#define BIF_md5_final_1 117
#define BIF_ebif_md5_final_1 118
#define BIF_memory_0 119
#define BIF_ebif_memory_0 120
#define BIF_memory_1 121
#define BIF_ebif_memory_1 122
#define BIF_module_loaded_1 123
#define BIF_ebif_is_loaded_1 124
#define BIF_function_exported_3 125
#define BIF_ebif_is_loaded_3 126
#define BIF_monitor_node_2 127
#define BIF_ebif_monitor_node_2 128
#define BIF_monitor_node_3 129
#define BIF_ebif_monitor_node_3 130
#define BIF_node_1 131
#define BIF_ebif_node_1 132
#define BIF_node_0 133
#define BIF_ebif_node_0 134
#define BIF_nodes_1 135
#define BIF_ebif_nodes_1 136
#define BIF_now_0 137
#define BIF_ebif_now_0 138
#define BIF_open_port_2 139
#define BIF_ebif_open_port_2 140
#define BIF_pid_to_list_1 141
#define BIF_ebif_pid_to_string_1 142
#define BIF_port_info_1 143
#define BIF_ebif_port_info_1 144
#define BIF_port_info_2 145
#define BIF_ebif_port_info_2 146
#define BIF_ports_0 147
#define BIF_ebif_ports_0 148
#define BIF_pre_loaded_0 149
#define BIF_ebif_pre_loaded_0 150
#define BIF_process_flag_2 151
#define BIF_ebif_process_flag_2 152
#define BIF_process_flag_3 153
#define BIF_ebif_process_flag_3 154
#define BIF_process_info_1 155
#define BIF_ebif_process_info_1 156
#define BIF_process_info_2 157
#define BIF_ebif_process_info_2 158
#define BIF_processes_0 159
#define BIF_ebif_processes_0 160
#define BIF_purge_module_1 161
#define BIF_ebif_purge_module_1 162
#define BIF_put_2 163
#define BIF_ebif_put_2 164
#define BIF_register_2 165
#define BIF_ebif_register_2 166
#define BIF_registered_0 167
#define BIF_ebif_registered_0 168
#define BIF_round_1 169
#define BIF_ebif_round_1 170
#define BIF_self_0 171
#define BIF_ebif_self_0 172
#define BIF_setelement_3 173
#define BIF_ebif_setelement_3 174
#define BIF_size_1 175
#define BIF_ebif_size_1 176
#define BIF_spawn_3 177
#define BIF_ebif_spawn_3 178
#define BIF_spawn_link_3 179
#define BIF_ebif_spawn_link_3 180
#define BIF_split_binary_2 181
#define BIF_ebif_split_binary_2 182
#define BIF_statistics_1 183
#define BIF_ebif_statistics_1 184
#define BIF_term_to_binary_1 185
#define BIF_ebif_term_to_binary_1 186
#define BIF_term_to_binary_2 187
#define BIF_ebif_term_to_binary_2 188
#define BIF_throw_1 189
#define BIF_ebif_throw_1 190
#define BIF_time_0 191
#define BIF_ebif_time_0 192
#define BIF_tl_1 193
#define BIF_ebif_tl_1 194
#define BIF_trunc_1 195
#define BIF_ebif_trunc_1 196
#define BIF_tuple_to_list_1 197
#define BIF_ebif_tuple_to_list_1 198
#define BIF_universaltime_0 199
#define BIF_ebif_universaltime_0 200
#define BIF_universaltime_to_localtime_1 201
#define BIF_ebif_universaltime_to_localtime_1 202
#define BIF_unlink_1 203
#define BIF_ebif_unlink_1 204
#define BIF_unregister_1 205
#define BIF_ebif_unregister_1 206
#define BIF_whereis_1 207
#define BIF_ebif_whereis_1 208
#define BIF_spawn_opt_1 209
#define BIF_ebif_spawn_opt_1 210
#define BIF_setnode_2 211
#define BIF_setnode_3 212
#define BIF_dist_exit_3 213
#define BIF_port_call_2 214
#define BIF_ebif_port_call_2 215
#define BIF_port_call_3 216
#define BIF_ebif_port_call_3 217
#define BIF_port_command_2 218
#define BIF_ebif_port_command_2 219
#define BIF_port_command_3 220
#define BIF_ebif_port_command_3 221
#define BIF_port_control_3 222
#define BIF_ebif_port_control_3 223
#define BIF_port_close_1 224
#define BIF_ebif_port_close_1 225
#define BIF_port_connect_2 226
#define BIF_ebif_port_connect_2 227
#define BIF_port_set_data_2 228
#define BIF_ebif_port_set_data_2 229
#define BIF_port_get_data_1 230
#define BIF_ebif_port_get_data_1 231
#define BIF_trace_pattern_2 232
#define BIF_ebif_trace_pattern_2 233
#define BIF_trace_pattern_3 234
#define BIF_ebif_trace_pattern_3 235
#define BIF_trace_3 236
#define BIF_ebif_trace_3 237
#define BIF_trace_info_2 238
#define BIF_ebif_trace_info_2 239
#define BIF_trace_delivered_1 240
#define BIF_ebif_trace_delivered_1 241
#define BIF_seq_trace_2 242
#define BIF_ebif_seq_trace_2 243
#define BIF_seq_trace_info_1 244
#define BIF_ebif_seq_trace_info_1 245
#define BIF_seq_trace_print_1 246
#define BIF_ebif_seq_trace_print_1 247
#define BIF_seq_trace_print_2 248
#define BIF_ebif_seq_trace_print_2 249
#define BIF_suspend_process_2 250
#define BIF_ebif_suspend_process_2 251
#define BIF_resume_process_1 252
#define BIF_ebif_resume_process_1 253
#define BIF_process_display_2 254
#define BIF_ebif_process_display_2 255
#define BIF_bump_reductions_1 256
#define BIF_ebif_bump_reductions_1 257
#define BIF_math_cos_1 258
#define BIF_ebif_math_cos_1 259
#define BIF_math_cosh_1 260
#define BIF_ebif_math_cosh_1 261
#define BIF_math_sin_1 262
#define BIF_ebif_math_sin_1 263
#define BIF_math_sinh_1 264
#define BIF_ebif_math_sinh_1 265
#define BIF_math_tan_1 266
#define BIF_ebif_math_tan_1 267
#define BIF_math_tanh_1 268
#define BIF_ebif_math_tanh_1 269
#define BIF_math_acos_1 270
#define BIF_ebif_math_acos_1 271
#define BIF_math_acosh_1 272
#define BIF_ebif_math_acosh_1 273
#define BIF_math_asin_1 274
#define BIF_ebif_math_asin_1 275
#define BIF_math_asinh_1 276
#define BIF_ebif_math_asinh_1 277
#define BIF_math_atan_1 278
#define BIF_ebif_math_atan_1 279
#define BIF_math_atanh_1 280
#define BIF_ebif_math_atanh_1 281
#define BIF_math_erf_1 282
#define BIF_ebif_math_erf_1 283
#define BIF_math_erfc_1 284
#define BIF_ebif_math_erfc_1 285
#define BIF_math_exp_1 286
#define BIF_ebif_math_exp_1 287
#define BIF_math_log_1 288
#define BIF_ebif_math_log_1 289
#define BIF_math_log10_1 290
#define BIF_ebif_math_log10_1 291
#define BIF_math_sqrt_1 292
#define BIF_ebif_math_sqrt_1 293
#define BIF_math_atan2_2 294
#define BIF_ebif_math_atan2_2 295
#define BIF_math_pow_2 296
#define BIF_ebif_math_pow_2 297
#define BIF_start_timer_3 298
#define BIF_ebif_start_timer_3 299
#define BIF_send_after_3 300
#define BIF_ebif_send_after_3 301
#define BIF_cancel_timer_1 302
#define BIF_ebif_cancel_timer_1 303
#define BIF_read_timer_1 304
#define BIF_ebif_read_timer_1 305
#define BIF_make_tuple_2 306
#define BIF_ebif_make_tuple_2 307
#define BIF_append_element_2 308
#define BIF_ebif_append_element_2 309
#define BIF_make_tuple_3 310
#define BIF_system_flag_2 311
#define BIF_ebif_system_flag_2 312
#define BIF_system_info_1 313
#define BIF_ebif_system_info_1 314
#define BIF_system_monitor_0 315
#define BIF_ebif_system_monitor_0 316
#define BIF_system_monitor_1 317
#define BIF_ebif_system_monitor_1 318
#define BIF_system_monitor_2 319
#define BIF_ebif_system_monitor_2 320
#define BIF_system_profile_2 321
#define BIF_ebif_system_profile_2 322
#define BIF_system_profile_0 323
#define BIF_ebif_system_profile_0 324
#define BIF_ref_to_list_1 325
#define BIF_ebif_ref_to_string_1 326
#define BIF_port_to_list_1 327
#define BIF_ebif_port_to_string_1 328
#define BIF_fun_to_list_1 329
#define BIF_ebif_fun_to_string_1 330
#define BIF_monitor_2 331
#define BIF_ebif_monitor_2 332
#define BIF_demonitor_1 333
#define BIF_ebif_demonitor_1 334
#define BIF_demonitor_2 335
#define BIF_ebif_demonitor_2 336
#define BIF_is_process_alive_1 337
#define BIF_ebif_proc_is_alive_1 338
#define BIF_error_1 339
#define BIF_ebif_error_1 340
#define BIF_error_2 341
#define BIF_ebif_error_2 342
#define BIF_raise_3 343
#define BIF_ebif_raise_3 344
#define BIF_get_stacktrace_0 345
#define BIF_ebif_get_stacktrace_0 346
#define BIF_is_builtin_3 347
#define BIF_ebif_is_builtin_3 348
#define BIF_and_2 349
#define BIF_ebif_and_2 350
#define BIF_or_2 351
#define BIF_ebif_or_2 352
#define BIF_xor_2 353
#define BIF_ebif_xor_2 354
#define BIF_not_1 355
#define BIF_ebif_not_1 356
#define BIF_sgt_2 357
#define BIF_ebif_gt_2 358
#define BIF_sge_2 359
#define BIF_ebif_ge_2 360
#define BIF_slt_2 361
#define BIF_ebif_lt_2 362
#define BIF_sle_2 363
#define BIF_ebif_le_2 364
#define BIF_seq_2 365
#define BIF_ebif_eq_2 366
#define BIF_seqeq_2 367
#define BIF_ebif_areq_2 368
#define BIF_sneq_2 369
#define BIF_ebif_neq_2 370
#define BIF_sneqeq_2 371
#define BIF_ebif_nareq_2 372
#define BIF_splus_2 373
#define BIF_ebif_plus_2 374
#define BIF_sminus_2 375
#define BIF_ebif_minus_2 376
#define BIF_stimes_2 377
#define BIF_ebif_multiply_2 378
#define BIF_div_2 379
#define BIF_ebif_divide_2 380
#define BIF_intdiv_2 381
#define BIF_ebif_intdiv_2 382
#define BIF_rem_2 383
#define BIF_ebif_rem_2 384
#define BIF_bor_2 385
#define BIF_ebif_bor_2 386
#define BIF_band_2 387
#define BIF_ebif_band_2 388
#define BIF_bxor_2 389
#define BIF_ebif_bxor_2 390
#define BIF_bsl_2 391
#define BIF_ebif_bsl_2 392
#define BIF_bsr_2 393
#define BIF_ebif_bsr_2 394
#define BIF_bnot_1 395
#define BIF_ebif_bnot_1 396
#define BIF_sminus_1 397
#define BIF_ebif_minus_1 398
#define BIF_splus_1 399
#define BIF_ebif_plus_1 400
#define BIF_ebif_bang_2 401
#define BIF_ebif_send_2 402
#define BIF_send_2 403
#define BIF_ebif_send_3 404
#define BIF_send_3 405
#define BIF_ebif_plusplus_2 406
#define BIF_ebif_append_2 407
#define BIF_append_2 408
#define BIF_ebif_minusminus_2 409
#define BIF_ebif_list_subtract_2 410
#define BIF_subtract_2 411
#define BIF_is_atom_1 412
#define BIF_ebif_is_atom_1 413
#define BIF_is_list_1 414
#define BIF_ebif_is_list_1 415
#define BIF_is_tuple_1 416
#define BIF_ebif_is_tuple_1 417
#define BIF_is_float_1 418
#define BIF_ebif_is_float_1 419
#define BIF_is_integer_1 420
#define BIF_ebif_is_integer_1 421
#define BIF_is_number_1 422
#define BIF_ebif_is_number_1 423
#define BIF_is_pid_1 424
#define BIF_ebif_is_pid_1 425
#define BIF_is_port_1 426
#define BIF_ebif_is_port_1 427
#define BIF_is_reference_1 428
#define BIF_ebif_is_reference_1 429
#define BIF_is_binary_1 430
#define BIF_ebif_is_binary_1 431
#define BIF_is_function_1 432
#define BIF_ebif_is_function_1 433
#define BIF_is_function_2 434
#define BIF_ebif_is_function_2 435
#define BIF_is_record_2 436
#define BIF_ebif_is_record_2 437
#define BIF_is_record_3 438
#define BIF_ebif_is_record_3 439
#define BIF_match_spec_test_3 440
#define BIF_ets_all_0 441
#define BIF_ebif_ets_all_0 442
#define BIF_ets_new_2 443
#define BIF_ebif_ets_new_2 444
#define BIF_ets_delete_1 445
#define BIF_ebif_ets_delete_1 446
#define BIF_ets_delete_2 447
#define BIF_ebif_ets_delete_2 448
#define BIF_ets_delete_all_objects_1 449
#define BIF_ebif_ets_delete_all_objects_1 450
#define BIF_ets_delete_object_2 451
#define BIF_ebif_ets_delete_object_2 452
#define BIF_ets_first_1 453
#define BIF_ebif_ets_first_1 454
#define BIF_ets_is_compiled_ms_1 455
#define BIF_ebif_ets_is_compiled_ms_1 456
#define BIF_ets_lookup_2 457
#define BIF_ebif_ets_lookup_2 458
#define BIF_ets_lookup_element_3 459
#define BIF_ebif_ets_lookup_element_3 460
#define BIF_ets_info_1 461
#define BIF_ebif_ets_info_1 462
#define BIF_ets_info_2 463
#define BIF_ebif_ets_info_2 464
#define BIF_ets_last_1 465
#define BIF_ebif_ets_last_1 466
#define BIF_ets_match_1 467
#define BIF_ebif_ets_match_1 468
#define BIF_ets_match_2 469
#define BIF_ebif_ets_match_2 470
#define BIF_ets_match_3 471
#define BIF_ebif_ets_match_3 472
#define BIF_ets_match_object_1 473
#define BIF_ebif_ets_match_object_1 474
#define BIF_ets_match_object_2 475
#define BIF_ebif_ets_match_object_2 476
#define BIF_ets_match_object_3 477
#define BIF_ebif_ets_match_object_3 478
#define BIF_ets_member_2 479
#define BIF_ebif_ets_member_2 480
#define BIF_ets_next_2 481
#define BIF_ebif_ets_next_2 482
#define BIF_ets_prev_2 483
#define BIF_ebif_ets_prev_2 484
#define BIF_ets_insert_2 485
#define BIF_ebif_ets_insert_2 486
#define BIF_ets_insert_new_2 487
#define BIF_ebif_ets_insert_new_2 488
#define BIF_ets_rename_2 489
#define BIF_ebif_ets_rename_2 490
#define BIF_ets_safe_fixtable_2 491
#define BIF_ebif_ets_safe_fixtable_2 492
#define BIF_ets_slot_2 493
#define BIF_ebif_ets_slot_2 494
#define BIF_ets_update_counter_3 495
#define BIF_ebif_ets_update_counter_3 496
#define BIF_ets_select_1 497
#define BIF_ebif_ets_select_1 498
#define BIF_ets_select_2 499
#define BIF_ebif_ets_select_2 500
#define BIF_ets_select_3 501
#define BIF_ebif_ets_select_3 502
#define BIF_ets_select_count_2 503
#define BIF_ebif_ets_select_count_2 504
#define BIF_ets_select_reverse_1 505
#define BIF_ebif_ets_select_reverse_1 506
#define BIF_ets_select_reverse_2 507
#define BIF_ebif_ets_select_reverse_2 508
#define BIF_ets_select_reverse_3 509
#define BIF_ebif_ets_select_reverse_3 510
#define BIF_ets_select_delete_2 511
#define BIF_ebif_ets_select_delete_2 512
#define BIF_ets_match_spec_compile_1 513
#define BIF_ebif_ets_match_spec_compile_1 514
#define BIF_ets_match_spec_run_r_3 515
#define BIF_ebif_ets_match_spec_run_r_3 516
#define BIF_os_putenv_2 517
#define BIF_ebif_os_setenv_2 518
#define BIF_os_getenv_0 519
#define BIF_ebif_os_getenv_0 520
#define BIF_os_getenv_1 521
#define BIF_ebif_os_getenv_1 522
#define BIF_os_getpid_0 523
#define BIF_ebif_os_pid_0 524
#define BIF_os_timestamp_0 525
#define BIF_ebif_os_timestamp_0 526
#define BIF_erl_ddll_try_load_3 527
#define BIF_erl_ddll_try_unload_2 528
#define BIF_erl_ddll_loaded_drivers_0 529
#define BIF_erl_ddll_info_2 530
#define BIF_erl_ddll_format_error_int_1 531
#define BIF_erl_ddll_monitor_2 532
#define BIF_erl_ddll_demonitor_1 533
#define BIF_re_compile_1 534
#define BIF_re_compile_2 535
#define BIF_re_run_2 536
#define BIF_re_run_3 537
#define BIF_lists_member_2 538
#define BIF_ebif_list_is_element_2 539
#define BIF_lists_reverse_2 540
#define BIF_ebif_list_reverse_2 541
#define BIF_lists_keymember_3 542
#define BIF_ebif_keylist_is_element_3 543
#define BIF_lists_keysearch_3 544
#define BIF_ebif_keylist_search_3 545
#define BIF_lists_keyfind_3 546
#define BIF_erts_debug_disassemble_1 547
#define BIF_ebif_erts_debug_disassemble_1 548
#define BIF_erts_debug_breakpoint_2 549
#define BIF_ebif_erts_debug_breakpoint_2 550
#define BIF_erts_debug_same_2 551
#define BIF_ebif_erts_debug_same_2 552
#define BIF_erts_debug_flat_size_1 553
#define BIF_ebif_erts_debug_flat_size_1 554
#define BIF_erts_debug_get_internal_state_1 555
#define BIF_ebif_erts_debug_get_internal_state_1 556
#define BIF_erts_debug_set_internal_state_2 557
#define BIF_ebif_erts_debug_set_internal_state_2 558
#define BIF_erts_debug_display_1 559
#define BIF_ebif_erts_debug_display_1 560
#define BIF_erts_debug_dist_ext_to_term_2 561
#define BIF_ebif_erts_debug_dist_ext_to_term_2 562
#define BIF_erts_debug_dump_monitors_1 563
#define BIF_erts_debug_dump_links_1 564
#define BIF_erts_debug_lock_counters_1 565
#define BIF_code_get_chunk_2 566
#define BIF_ebif_code_get_chunk_2 567
#define BIF_code_module_md5_1 568
#define BIF_ebif_code_module_md5_1 569
#define BIF_code_make_stub_module_3 570
#define BIF_ebif_code_make_stub_module_3 571
#define BIF_code_is_module_native_1 572
#define BIF_ebif_code_is_native_1 573
#define BIF_hibernate_3 574
#define BIF_error_logger_warning_map_0 575
#define BIF_get_module_info_1 576
#define BIF_get_module_info_2 577
#define BIF_is_boolean_1 578
#define BIF_string_to_integer_1 579
#define BIF_string_to_float_1 580
#define BIF_make_fun_3 581
#define BIF_iolist_size_1 582
#define BIF_iolist_to_binary_1 583
#define BIF_list_to_existing_atom_1 584
#define BIF_is_bitstring_1 585
#define BIF_tuple_size_1 586
#define BIF_byte_size_1 587
#define BIF_bit_size_1 588
#define BIF_list_to_bitstring_1 589
#define BIF_bitstring_to_list_1 590
#define BIF_ets_update_element_3 591
#define BIF_decode_packet_3 592
#define BIF_unicode_characters_to_binary_2 593
#define BIF_unicode_characters_to_list_2 594
#define BIF_unicode_bin_is_7bit_1 595
#define BIF_atom_to_binary_2 596
#define BIF_binary_to_atom_2 597
#define BIF_binary_to_existing_atom_2 598
#define BIF_net_kernel_dflag_unicode_io_1 599
#define BIF_ets_give_away_3 600
#define BIF_ets_setopts_2 601
#define BIF_load_nif_2 602
#define BIF_call_on_load_function_1 603
#define BIF_finish_after_on_load_2 604
#define BIF_binary_to_term_2 605
#define BIF_binary_part_2 606
#define BIF_binary_part_3 607
#define BIF_binary_compile_pattern_1 608
#define BIF_binary_match_2 609
#define BIF_binary_match_3 610
#define BIF_binary_matches_2 611
#define BIF_binary_matches_3 612
#define BIF_binary_longest_common_prefix_1 613
#define BIF_binary_longest_common_suffix_1 614
#define BIF_binary_first_1 615
#define BIF_binary_last_1 616
#define BIF_binary_at_2 617
#define BIF_binary_binary_part_2 618
#define BIF_binary_binary_part_3 619
#define BIF_binary_bin_to_list_1 620
#define BIF_binary_bin_to_list_2 621
#define BIF_binary_bin_to_list_3 622
#define BIF_binary_list_to_bin_1 623
#define BIF_binary_copy_1 624
#define BIF_binary_copy_2 625
#define BIF_binary_referenced_byte_size_1 626
#define BIF_binary_encode_unsigned_1 627
#define BIF_binary_encode_unsigned_2 628
#define BIF_binary_decode_unsigned_1 629
#define BIF_binary_decode_unsigned_2 630
#define BIF_nif_error_1 631
#define BIF_nif_error_2 632
#define BIF_hash_2 633

Eterm abs_1(Process*, Eterm);
Eterm wrap_abs_1(Process*, Eterm, UWord *I);
Eterm ebif_abs_1(Process*, Eterm);
Eterm wrap_ebif_abs_1(Process*, Eterm, UWord *I);
Eterm adler32_1(Process*, Eterm);
Eterm wrap_adler32_1(Process*, Eterm, UWord *I);
Eterm ebif_adler32_1(Process*, Eterm);
Eterm wrap_ebif_adler32_1(Process*, Eterm, UWord *I);
Eterm adler32_2(Process*, Eterm, Eterm);
Eterm wrap_adler32_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_adler32_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_adler32_2(Process*, Eterm, Eterm, UWord *I);
Eterm adler32_combine_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_adler32_combine_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ebif_adler32_combine_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ebif_adler32_combine_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm apply_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_apply_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ebif_apply_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ebif_apply_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm atom_to_list_1(Process*, Eterm);
Eterm wrap_atom_to_list_1(Process*, Eterm, UWord *I);
Eterm ebif_atom_to_string_1(Process*, Eterm);
Eterm wrap_ebif_atom_to_string_1(Process*, Eterm, UWord *I);
Eterm binary_to_list_1(Process*, Eterm);
Eterm wrap_binary_to_list_1(Process*, Eterm, UWord *I);
Eterm ebif_binary_to_list_1(Process*, Eterm);
Eterm wrap_ebif_binary_to_list_1(Process*, Eterm, UWord *I);
Eterm binary_to_list_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_binary_to_list_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ebif_binary_to_list_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ebif_binary_to_list_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm binary_to_term_1(Process*, Eterm);
Eterm wrap_binary_to_term_1(Process*, Eterm, UWord *I);
Eterm ebif_binary_to_term_1(Process*, Eterm);
Eterm wrap_ebif_binary_to_term_1(Process*, Eterm, UWord *I);
Eterm check_process_code_2(Process*, Eterm, Eterm);
Eterm wrap_check_process_code_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_check_process_code_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_check_process_code_2(Process*, Eterm, Eterm, UWord *I);
Eterm crc32_1(Process*, Eterm);
Eterm wrap_crc32_1(Process*, Eterm, UWord *I);
Eterm ebif_crc32_1(Process*, Eterm);
Eterm wrap_ebif_crc32_1(Process*, Eterm, UWord *I);
Eterm crc32_2(Process*, Eterm, Eterm);
Eterm wrap_crc32_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_crc32_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_crc32_2(Process*, Eterm, Eterm, UWord *I);
Eterm crc32_combine_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_crc32_combine_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ebif_crc32_combine_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ebif_crc32_combine_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm date_0(Process*);
Eterm wrap_date_0(Process*, UWord *I);
Eterm ebif_date_0(Process*);
Eterm wrap_ebif_date_0(Process*, UWord *I);
Eterm delete_module_1(Process*, Eterm);
Eterm wrap_delete_module_1(Process*, Eterm, UWord *I);
Eterm ebif_delete_module_1(Process*, Eterm);
Eterm wrap_ebif_delete_module_1(Process*, Eterm, UWord *I);
Eterm display_1(Process*, Eterm);
Eterm wrap_display_1(Process*, Eterm, UWord *I);
Eterm ebif_display_1(Process*, Eterm);
Eterm wrap_ebif_display_1(Process*, Eterm, UWord *I);
Eterm display_string_1(Process*, Eterm);
Eterm wrap_display_string_1(Process*, Eterm, UWord *I);
Eterm ebif_display_string_1(Process*, Eterm);
Eterm wrap_ebif_display_string_1(Process*, Eterm, UWord *I);
Eterm display_nl_0(Process*);
Eterm wrap_display_nl_0(Process*, UWord *I);
Eterm ebif_display_nl_0(Process*);
Eterm wrap_ebif_display_nl_0(Process*, UWord *I);
Eterm element_2(Process*, Eterm, Eterm);
Eterm wrap_element_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_element_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_element_2(Process*, Eterm, Eterm, UWord *I);
Eterm erase_0(Process*);
Eterm wrap_erase_0(Process*, UWord *I);
Eterm ebif_erase_0(Process*);
Eterm wrap_ebif_erase_0(Process*, UWord *I);
Eterm erase_1(Process*, Eterm);
Eterm wrap_erase_1(Process*, Eterm, UWord *I);
Eterm ebif_erase_1(Process*, Eterm);
Eterm wrap_ebif_erase_1(Process*, Eterm, UWord *I);
Eterm exit_1(Process*, Eterm);
Eterm wrap_exit_1(Process*, Eterm, UWord *I);
Eterm ebif_exit_1(Process*, Eterm);
Eterm wrap_ebif_exit_1(Process*, Eterm, UWord *I);
Eterm exit_2(Process*, Eterm, Eterm);
Eterm wrap_exit_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_signal_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_signal_2(Process*, Eterm, Eterm, UWord *I);
Eterm external_size_1(Process*, Eterm);
Eterm wrap_external_size_1(Process*, Eterm, UWord *I);
Eterm ebif_external_size_1(Process*, Eterm);
Eterm wrap_ebif_external_size_1(Process*, Eterm, UWord *I);
Eterm float_1(Process*, Eterm);
Eterm wrap_float_1(Process*, Eterm, UWord *I);
Eterm ebif_to_float_1(Process*, Eterm);
Eterm wrap_ebif_to_float_1(Process*, Eterm, UWord *I);
Eterm float_to_list_1(Process*, Eterm);
Eterm wrap_float_to_list_1(Process*, Eterm, UWord *I);
Eterm ebif_float_to_string_1(Process*, Eterm);
Eterm wrap_ebif_float_to_string_1(Process*, Eterm, UWord *I);
Eterm fun_info_2(Process*, Eterm, Eterm);
Eterm wrap_fun_info_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_fun_info_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_fun_info_2(Process*, Eterm, Eterm, UWord *I);
Eterm garbage_collect_0(Process*);
Eterm wrap_garbage_collect_0(Process*, UWord *I);
Eterm ebif_garbage_collect_0(Process*);
Eterm wrap_ebif_garbage_collect_0(Process*, UWord *I);
Eterm garbage_collect_1(Process*, Eterm);
Eterm wrap_garbage_collect_1(Process*, Eterm, UWord *I);
Eterm ebif_garbage_collect_1(Process*, Eterm);
Eterm wrap_ebif_garbage_collect_1(Process*, Eterm, UWord *I);
Eterm garbage_collect_message_area_0(Process*);
Eterm wrap_garbage_collect_message_area_0(Process*, UWord *I);
Eterm ebif_garbage_collect_message_area_0(Process*);
Eterm wrap_ebif_garbage_collect_message_area_0(Process*, UWord *I);
Eterm get_0(Process*);
Eterm wrap_get_0(Process*, UWord *I);
Eterm ebif_get_0(Process*);
Eterm wrap_ebif_get_0(Process*, UWord *I);
Eterm get_1(Process*, Eterm);
Eterm wrap_get_1(Process*, Eterm, UWord *I);
Eterm ebif_get_1(Process*, Eterm);
Eterm wrap_ebif_get_1(Process*, Eterm, UWord *I);
Eterm get_keys_1(Process*, Eterm);
Eterm wrap_get_keys_1(Process*, Eterm, UWord *I);
Eterm ebif_get_keys_1(Process*, Eterm);
Eterm wrap_ebif_get_keys_1(Process*, Eterm, UWord *I);
Eterm group_leader_0(Process*);
Eterm wrap_group_leader_0(Process*, UWord *I);
Eterm ebif_group_leader_0(Process*);
Eterm wrap_ebif_group_leader_0(Process*, UWord *I);
Eterm group_leader_2(Process*, Eterm, Eterm);
Eterm wrap_group_leader_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_group_leader_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_group_leader_2(Process*, Eterm, Eterm, UWord *I);
Eterm halt_0(Process*);
Eterm wrap_halt_0(Process*, UWord *I);
Eterm ebif_halt_0(Process*);
Eterm wrap_ebif_halt_0(Process*, UWord *I);
Eterm halt_1(Process*, Eterm);
Eterm wrap_halt_1(Process*, Eterm, UWord *I);
Eterm ebif_halt_1(Process*, Eterm);
Eterm wrap_ebif_halt_1(Process*, Eterm, UWord *I);
Eterm phash_2(Process*, Eterm, Eterm);
Eterm wrap_phash_2(Process*, Eterm, Eterm, UWord *I);
Eterm phash2_1(Process*, Eterm);
Eterm wrap_phash2_1(Process*, Eterm, UWord *I);
Eterm phash2_2(Process*, Eterm, Eterm);
Eterm wrap_phash2_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_phash2_1(Process*, Eterm);
Eterm wrap_ebif_phash2_1(Process*, Eterm, UWord *I);
Eterm ebif_phash2_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_phash2_2(Process*, Eterm, Eterm, UWord *I);
Eterm hd_1(Process*, Eterm);
Eterm wrap_hd_1(Process*, Eterm, UWord *I);
Eterm ebif_hd_1(Process*, Eterm);
Eterm wrap_ebif_hd_1(Process*, Eterm, UWord *I);
Eterm integer_to_list_1(Process*, Eterm);
Eterm wrap_integer_to_list_1(Process*, Eterm, UWord *I);
Eterm ebif_integer_to_string_1(Process*, Eterm);
Eterm wrap_ebif_integer_to_string_1(Process*, Eterm, UWord *I);
Eterm is_alive_0(Process*);
Eterm wrap_is_alive_0(Process*, UWord *I);
Eterm ebif_is_alive_0(Process*);
Eterm wrap_ebif_is_alive_0(Process*, UWord *I);
Eterm length_1(Process*, Eterm);
Eterm wrap_length_1(Process*, Eterm, UWord *I);
Eterm ebif_length_1(Process*, Eterm);
Eterm wrap_ebif_length_1(Process*, Eterm, UWord *I);
Eterm link_1(Process*, Eterm);
Eterm wrap_link_1(Process*, Eterm, UWord *I);
Eterm ebif_link_1(Process*, Eterm);
Eterm wrap_ebif_link_1(Process*, Eterm, UWord *I);
Eterm list_to_atom_1(Process*, Eterm);
Eterm wrap_list_to_atom_1(Process*, Eterm, UWord *I);
Eterm ebif_string_to_atom_1(Process*, Eterm);
Eterm wrap_ebif_string_to_atom_1(Process*, Eterm, UWord *I);
Eterm list_to_binary_1(Process*, Eterm);
Eterm wrap_list_to_binary_1(Process*, Eterm, UWord *I);
Eterm ebif_list_to_binary_1(Process*, Eterm);
Eterm wrap_ebif_list_to_binary_1(Process*, Eterm, UWord *I);
Eterm list_to_float_1(Process*, Eterm);
Eterm wrap_list_to_float_1(Process*, Eterm, UWord *I);
Eterm ebif_string_to_float_1(Process*, Eterm);
Eterm wrap_ebif_string_to_float_1(Process*, Eterm, UWord *I);
Eterm list_to_integer_1(Process*, Eterm);
Eterm wrap_list_to_integer_1(Process*, Eterm, UWord *I);
Eterm ebif_string_to_integer_1(Process*, Eterm);
Eterm wrap_ebif_string_to_integer_1(Process*, Eterm, UWord *I);
Eterm list_to_pid_1(Process*, Eterm);
Eterm wrap_list_to_pid_1(Process*, Eterm, UWord *I);
Eterm ebif_string_to_pid_1(Process*, Eterm);
Eterm wrap_ebif_string_to_pid_1(Process*, Eterm, UWord *I);
Eterm list_to_tuple_1(Process*, Eterm);
Eterm wrap_list_to_tuple_1(Process*, Eterm, UWord *I);
Eterm ebif_list_to_tuple_1(Process*, Eterm);
Eterm wrap_ebif_list_to_tuple_1(Process*, Eterm, UWord *I);
Eterm load_module_2(Process*, Eterm, Eterm);
Eterm wrap_load_module_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_load_module_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_load_module_2(Process*, Eterm, Eterm, UWord *I);
Eterm loaded_0(Process*);
Eterm wrap_loaded_0(Process*, UWord *I);
Eterm ebif_loaded_0(Process*);
Eterm wrap_ebif_loaded_0(Process*, UWord *I);
Eterm localtime_0(Process*);
Eterm wrap_localtime_0(Process*, UWord *I);
Eterm ebif_localtime_0(Process*);
Eterm wrap_ebif_localtime_0(Process*, UWord *I);
Eterm localtime_to_universaltime_2(Process*, Eterm, Eterm);
Eterm wrap_localtime_to_universaltime_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_localtime_to_universaltime_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_localtime_to_universaltime_2(Process*, Eterm, Eterm, UWord *I);
Eterm make_ref_0(Process*);
Eterm wrap_make_ref_0(Process*, UWord *I);
Eterm ebif_make_ref_0(Process*);
Eterm wrap_ebif_make_ref_0(Process*, UWord *I);
Eterm md5_1(Process*, Eterm);
Eterm wrap_md5_1(Process*, Eterm, UWord *I);
Eterm ebif_md5_1(Process*, Eterm);
Eterm wrap_ebif_md5_1(Process*, Eterm, UWord *I);
Eterm md5_init_0(Process*);
Eterm wrap_md5_init_0(Process*, UWord *I);
Eterm ebif_md5_init_0(Process*);
Eterm wrap_ebif_md5_init_0(Process*, UWord *I);
Eterm md5_update_2(Process*, Eterm, Eterm);
Eterm wrap_md5_update_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_md5_update_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_md5_update_2(Process*, Eterm, Eterm, UWord *I);
Eterm md5_final_1(Process*, Eterm);
Eterm wrap_md5_final_1(Process*, Eterm, UWord *I);
Eterm ebif_md5_final_1(Process*, Eterm);
Eterm wrap_ebif_md5_final_1(Process*, Eterm, UWord *I);
Eterm memory_0(Process*);
Eterm wrap_memory_0(Process*, UWord *I);
Eterm ebif_memory_0(Process*);
Eterm wrap_ebif_memory_0(Process*, UWord *I);
Eterm memory_1(Process*, Eterm);
Eterm wrap_memory_1(Process*, Eterm, UWord *I);
Eterm ebif_memory_1(Process*, Eterm);
Eterm wrap_ebif_memory_1(Process*, Eterm, UWord *I);
Eterm module_loaded_1(Process*, Eterm);
Eterm wrap_module_loaded_1(Process*, Eterm, UWord *I);
Eterm ebif_is_loaded_1(Process*, Eterm);
Eterm wrap_ebif_is_loaded_1(Process*, Eterm, UWord *I);
Eterm function_exported_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_function_exported_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ebif_is_loaded_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ebif_is_loaded_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm monitor_node_2(Process*, Eterm, Eterm);
Eterm wrap_monitor_node_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_monitor_node_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_monitor_node_2(Process*, Eterm, Eterm, UWord *I);
Eterm monitor_node_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_monitor_node_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ebif_monitor_node_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ebif_monitor_node_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm node_1(Process*, Eterm);
Eterm wrap_node_1(Process*, Eterm, UWord *I);
Eterm ebif_node_1(Process*, Eterm);
Eterm wrap_ebif_node_1(Process*, Eterm, UWord *I);
Eterm node_0(Process*);
Eterm wrap_node_0(Process*, UWord *I);
Eterm ebif_node_0(Process*);
Eterm wrap_ebif_node_0(Process*, UWord *I);
Eterm nodes_1(Process*, Eterm);
Eterm wrap_nodes_1(Process*, Eterm, UWord *I);
Eterm ebif_nodes_1(Process*, Eterm);
Eterm wrap_ebif_nodes_1(Process*, Eterm, UWord *I);
Eterm now_0(Process*);
Eterm wrap_now_0(Process*, UWord *I);
Eterm ebif_now_0(Process*);
Eterm wrap_ebif_now_0(Process*, UWord *I);
Eterm open_port_2(Process*, Eterm, Eterm);
Eterm wrap_open_port_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_open_port_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_open_port_2(Process*, Eterm, Eterm, UWord *I);
Eterm pid_to_list_1(Process*, Eterm);
Eterm wrap_pid_to_list_1(Process*, Eterm, UWord *I);
Eterm ebif_pid_to_string_1(Process*, Eterm);
Eterm wrap_ebif_pid_to_string_1(Process*, Eterm, UWord *I);
Eterm port_info_1(Process*, Eterm);
Eterm wrap_port_info_1(Process*, Eterm, UWord *I);
Eterm ebif_port_info_1(Process*, Eterm);
Eterm wrap_ebif_port_info_1(Process*, Eterm, UWord *I);
Eterm port_info_2(Process*, Eterm, Eterm);
Eterm wrap_port_info_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_port_info_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_port_info_2(Process*, Eterm, Eterm, UWord *I);
Eterm ports_0(Process*);
Eterm wrap_ports_0(Process*, UWord *I);
Eterm ebif_ports_0(Process*);
Eterm wrap_ebif_ports_0(Process*, UWord *I);
Eterm pre_loaded_0(Process*);
Eterm wrap_pre_loaded_0(Process*, UWord *I);
Eterm ebif_pre_loaded_0(Process*);
Eterm wrap_ebif_pre_loaded_0(Process*, UWord *I);
Eterm process_flag_2(Process*, Eterm, Eterm);
Eterm wrap_process_flag_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_process_flag_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_process_flag_2(Process*, Eterm, Eterm, UWord *I);
Eterm process_flag_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_process_flag_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ebif_process_flag_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ebif_process_flag_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm process_info_1(Process*, Eterm);
Eterm wrap_process_info_1(Process*, Eterm, UWord *I);
Eterm ebif_process_info_1(Process*, Eterm);
Eterm wrap_ebif_process_info_1(Process*, Eterm, UWord *I);
Eterm process_info_2(Process*, Eterm, Eterm);
Eterm wrap_process_info_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_process_info_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_process_info_2(Process*, Eterm, Eterm, UWord *I);
Eterm processes_0(Process*);
Eterm wrap_processes_0(Process*, UWord *I);
Eterm ebif_processes_0(Process*);
Eterm wrap_ebif_processes_0(Process*, UWord *I);
Eterm purge_module_1(Process*, Eterm);
Eterm wrap_purge_module_1(Process*, Eterm, UWord *I);
Eterm ebif_purge_module_1(Process*, Eterm);
Eterm wrap_ebif_purge_module_1(Process*, Eterm, UWord *I);
Eterm put_2(Process*, Eterm, Eterm);
Eterm wrap_put_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_put_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_put_2(Process*, Eterm, Eterm, UWord *I);
Eterm register_2(Process*, Eterm, Eterm);
Eterm wrap_register_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_register_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_register_2(Process*, Eterm, Eterm, UWord *I);
Eterm registered_0(Process*);
Eterm wrap_registered_0(Process*, UWord *I);
Eterm ebif_registered_0(Process*);
Eterm wrap_ebif_registered_0(Process*, UWord *I);
Eterm round_1(Process*, Eterm);
Eterm wrap_round_1(Process*, Eterm, UWord *I);
Eterm ebif_round_1(Process*, Eterm);
Eterm wrap_ebif_round_1(Process*, Eterm, UWord *I);
Eterm self_0(Process*);
Eterm wrap_self_0(Process*, UWord *I);
Eterm ebif_self_0(Process*);
Eterm wrap_ebif_self_0(Process*, UWord *I);
Eterm setelement_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_setelement_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ebif_setelement_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ebif_setelement_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm size_1(Process*, Eterm);
Eterm wrap_size_1(Process*, Eterm, UWord *I);
Eterm ebif_size_1(Process*, Eterm);
Eterm wrap_ebif_size_1(Process*, Eterm, UWord *I);
Eterm spawn_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_spawn_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ebif_spawn_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ebif_spawn_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm spawn_link_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_spawn_link_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ebif_spawn_link_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ebif_spawn_link_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm split_binary_2(Process*, Eterm, Eterm);
Eterm wrap_split_binary_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_split_binary_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_split_binary_2(Process*, Eterm, Eterm, UWord *I);
Eterm statistics_1(Process*, Eterm);
Eterm wrap_statistics_1(Process*, Eterm, UWord *I);
Eterm ebif_statistics_1(Process*, Eterm);
Eterm wrap_ebif_statistics_1(Process*, Eterm, UWord *I);
Eterm term_to_binary_1(Process*, Eterm);
Eterm wrap_term_to_binary_1(Process*, Eterm, UWord *I);
Eterm ebif_term_to_binary_1(Process*, Eterm);
Eterm wrap_ebif_term_to_binary_1(Process*, Eterm, UWord *I);
Eterm term_to_binary_2(Process*, Eterm, Eterm);
Eterm wrap_term_to_binary_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_term_to_binary_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_term_to_binary_2(Process*, Eterm, Eterm, UWord *I);
Eterm throw_1(Process*, Eterm);
Eterm wrap_throw_1(Process*, Eterm, UWord *I);
Eterm ebif_throw_1(Process*, Eterm);
Eterm wrap_ebif_throw_1(Process*, Eterm, UWord *I);
Eterm time_0(Process*);
Eterm wrap_time_0(Process*, UWord *I);
Eterm ebif_time_0(Process*);
Eterm wrap_ebif_time_0(Process*, UWord *I);
Eterm tl_1(Process*, Eterm);
Eterm wrap_tl_1(Process*, Eterm, UWord *I);
Eterm ebif_tl_1(Process*, Eterm);
Eterm wrap_ebif_tl_1(Process*, Eterm, UWord *I);
Eterm trunc_1(Process*, Eterm);
Eterm wrap_trunc_1(Process*, Eterm, UWord *I);
Eterm ebif_trunc_1(Process*, Eterm);
Eterm wrap_ebif_trunc_1(Process*, Eterm, UWord *I);
Eterm tuple_to_list_1(Process*, Eterm);
Eterm wrap_tuple_to_list_1(Process*, Eterm, UWord *I);
Eterm ebif_tuple_to_list_1(Process*, Eterm);
Eterm wrap_ebif_tuple_to_list_1(Process*, Eterm, UWord *I);
Eterm universaltime_0(Process*);
Eterm wrap_universaltime_0(Process*, UWord *I);
Eterm ebif_universaltime_0(Process*);
Eterm wrap_ebif_universaltime_0(Process*, UWord *I);
Eterm universaltime_to_localtime_1(Process*, Eterm);
Eterm wrap_universaltime_to_localtime_1(Process*, Eterm, UWord *I);
Eterm ebif_universaltime_to_localtime_1(Process*, Eterm);
Eterm wrap_ebif_universaltime_to_localtime_1(Process*, Eterm, UWord *I);
Eterm unlink_1(Process*, Eterm);
Eterm wrap_unlink_1(Process*, Eterm, UWord *I);
Eterm ebif_unlink_1(Process*, Eterm);
Eterm wrap_ebif_unlink_1(Process*, Eterm, UWord *I);
Eterm unregister_1(Process*, Eterm);
Eterm wrap_unregister_1(Process*, Eterm, UWord *I);
Eterm ebif_unregister_1(Process*, Eterm);
Eterm wrap_ebif_unregister_1(Process*, Eterm, UWord *I);
Eterm whereis_1(Process*, Eterm);
Eterm wrap_whereis_1(Process*, Eterm, UWord *I);
Eterm ebif_whereis_1(Process*, Eterm);
Eterm wrap_ebif_whereis_1(Process*, Eterm, UWord *I);
Eterm spawn_opt_1(Process*, Eterm);
Eterm wrap_spawn_opt_1(Process*, Eterm, UWord *I);
Eterm ebif_spawn_opt_1(Process*, Eterm);
Eterm wrap_ebif_spawn_opt_1(Process*, Eterm, UWord *I);
Eterm setnode_2(Process*, Eterm, Eterm);
Eterm wrap_setnode_2(Process*, Eterm, Eterm, UWord *I);
Eterm setnode_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_setnode_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm dist_exit_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_dist_exit_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm port_call_2(Process*, Eterm, Eterm);
Eterm wrap_port_call_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_port_call_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_port_call_2(Process*, Eterm, Eterm, UWord *I);
Eterm port_call_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_port_call_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ebif_port_call_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ebif_port_call_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm port_command_2(Process*, Eterm, Eterm);
Eterm wrap_port_command_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_port_command_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_port_command_2(Process*, Eterm, Eterm, UWord *I);
Eterm port_command_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_port_command_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ebif_port_command_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ebif_port_command_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm port_control_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_port_control_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ebif_port_control_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ebif_port_control_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm port_close_1(Process*, Eterm);
Eterm wrap_port_close_1(Process*, Eterm, UWord *I);
Eterm ebif_port_close_1(Process*, Eterm);
Eterm wrap_ebif_port_close_1(Process*, Eterm, UWord *I);
Eterm port_connect_2(Process*, Eterm, Eterm);
Eterm wrap_port_connect_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_port_connect_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_port_connect_2(Process*, Eterm, Eterm, UWord *I);
Eterm port_set_data_2(Process*, Eterm, Eterm);
Eterm wrap_port_set_data_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_port_set_data_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_port_set_data_2(Process*, Eterm, Eterm, UWord *I);
Eterm port_get_data_1(Process*, Eterm);
Eterm wrap_port_get_data_1(Process*, Eterm, UWord *I);
Eterm ebif_port_get_data_1(Process*, Eterm);
Eterm wrap_ebif_port_get_data_1(Process*, Eterm, UWord *I);
Eterm trace_pattern_2(Process*, Eterm, Eterm);
Eterm wrap_trace_pattern_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_trace_pattern_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_trace_pattern_2(Process*, Eterm, Eterm, UWord *I);
Eterm trace_pattern_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_trace_pattern_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ebif_trace_pattern_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ebif_trace_pattern_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm trace_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_trace_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ebif_trace_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ebif_trace_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm trace_info_2(Process*, Eterm, Eterm);
Eterm wrap_trace_info_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_trace_info_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_trace_info_2(Process*, Eterm, Eterm, UWord *I);
Eterm trace_delivered_1(Process*, Eterm);
Eterm wrap_trace_delivered_1(Process*, Eterm, UWord *I);
Eterm ebif_trace_delivered_1(Process*, Eterm);
Eterm wrap_ebif_trace_delivered_1(Process*, Eterm, UWord *I);
Eterm seq_trace_2(Process*, Eterm, Eterm);
Eterm wrap_seq_trace_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_seq_trace_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_seq_trace_2(Process*, Eterm, Eterm, UWord *I);
Eterm seq_trace_info_1(Process*, Eterm);
Eterm wrap_seq_trace_info_1(Process*, Eterm, UWord *I);
Eterm ebif_seq_trace_info_1(Process*, Eterm);
Eterm wrap_ebif_seq_trace_info_1(Process*, Eterm, UWord *I);
Eterm seq_trace_print_1(Process*, Eterm);
Eterm wrap_seq_trace_print_1(Process*, Eterm, UWord *I);
Eterm ebif_seq_trace_print_1(Process*, Eterm);
Eterm wrap_ebif_seq_trace_print_1(Process*, Eterm, UWord *I);
Eterm seq_trace_print_2(Process*, Eterm, Eterm);
Eterm wrap_seq_trace_print_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_seq_trace_print_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_seq_trace_print_2(Process*, Eterm, Eterm, UWord *I);
Eterm suspend_process_2(Process*, Eterm, Eterm);
Eterm wrap_suspend_process_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_suspend_process_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_suspend_process_2(Process*, Eterm, Eterm, UWord *I);
Eterm resume_process_1(Process*, Eterm);
Eterm wrap_resume_process_1(Process*, Eterm, UWord *I);
Eterm ebif_resume_process_1(Process*, Eterm);
Eterm wrap_ebif_resume_process_1(Process*, Eterm, UWord *I);
Eterm process_display_2(Process*, Eterm, Eterm);
Eterm wrap_process_display_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_process_display_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_process_display_2(Process*, Eterm, Eterm, UWord *I);
Eterm bump_reductions_1(Process*, Eterm);
Eterm wrap_bump_reductions_1(Process*, Eterm, UWord *I);
Eterm ebif_bump_reductions_1(Process*, Eterm);
Eterm wrap_ebif_bump_reductions_1(Process*, Eterm, UWord *I);
Eterm math_cos_1(Process*, Eterm);
Eterm wrap_math_cos_1(Process*, Eterm, UWord *I);
Eterm ebif_math_cos_1(Process*, Eterm);
Eterm wrap_ebif_math_cos_1(Process*, Eterm, UWord *I);
Eterm math_cosh_1(Process*, Eterm);
Eterm wrap_math_cosh_1(Process*, Eterm, UWord *I);
Eterm ebif_math_cosh_1(Process*, Eterm);
Eterm wrap_ebif_math_cosh_1(Process*, Eterm, UWord *I);
Eterm math_sin_1(Process*, Eterm);
Eterm wrap_math_sin_1(Process*, Eterm, UWord *I);
Eterm ebif_math_sin_1(Process*, Eterm);
Eterm wrap_ebif_math_sin_1(Process*, Eterm, UWord *I);
Eterm math_sinh_1(Process*, Eterm);
Eterm wrap_math_sinh_1(Process*, Eterm, UWord *I);
Eterm ebif_math_sinh_1(Process*, Eterm);
Eterm wrap_ebif_math_sinh_1(Process*, Eterm, UWord *I);
Eterm math_tan_1(Process*, Eterm);
Eterm wrap_math_tan_1(Process*, Eterm, UWord *I);
Eterm ebif_math_tan_1(Process*, Eterm);
Eterm wrap_ebif_math_tan_1(Process*, Eterm, UWord *I);
Eterm math_tanh_1(Process*, Eterm);
Eterm wrap_math_tanh_1(Process*, Eterm, UWord *I);
Eterm ebif_math_tanh_1(Process*, Eterm);
Eterm wrap_ebif_math_tanh_1(Process*, Eterm, UWord *I);
Eterm math_acos_1(Process*, Eterm);
Eterm wrap_math_acos_1(Process*, Eterm, UWord *I);
Eterm ebif_math_acos_1(Process*, Eterm);
Eterm wrap_ebif_math_acos_1(Process*, Eterm, UWord *I);
Eterm math_acosh_1(Process*, Eterm);
Eterm wrap_math_acosh_1(Process*, Eterm, UWord *I);
Eterm ebif_math_acosh_1(Process*, Eterm);
Eterm wrap_ebif_math_acosh_1(Process*, Eterm, UWord *I);
Eterm math_asin_1(Process*, Eterm);
Eterm wrap_math_asin_1(Process*, Eterm, UWord *I);
Eterm ebif_math_asin_1(Process*, Eterm);
Eterm wrap_ebif_math_asin_1(Process*, Eterm, UWord *I);
Eterm math_asinh_1(Process*, Eterm);
Eterm wrap_math_asinh_1(Process*, Eterm, UWord *I);
Eterm ebif_math_asinh_1(Process*, Eterm);
Eterm wrap_ebif_math_asinh_1(Process*, Eterm, UWord *I);
Eterm math_atan_1(Process*, Eterm);
Eterm wrap_math_atan_1(Process*, Eterm, UWord *I);
Eterm ebif_math_atan_1(Process*, Eterm);
Eterm wrap_ebif_math_atan_1(Process*, Eterm, UWord *I);
Eterm math_atanh_1(Process*, Eterm);
Eterm wrap_math_atanh_1(Process*, Eterm, UWord *I);
Eterm ebif_math_atanh_1(Process*, Eterm);
Eterm wrap_ebif_math_atanh_1(Process*, Eterm, UWord *I);
Eterm math_erf_1(Process*, Eterm);
Eterm wrap_math_erf_1(Process*, Eterm, UWord *I);
Eterm ebif_math_erf_1(Process*, Eterm);
Eterm wrap_ebif_math_erf_1(Process*, Eterm, UWord *I);
Eterm math_erfc_1(Process*, Eterm);
Eterm wrap_math_erfc_1(Process*, Eterm, UWord *I);
Eterm ebif_math_erfc_1(Process*, Eterm);
Eterm wrap_ebif_math_erfc_1(Process*, Eterm, UWord *I);
Eterm math_exp_1(Process*, Eterm);
Eterm wrap_math_exp_1(Process*, Eterm, UWord *I);
Eterm ebif_math_exp_1(Process*, Eterm);
Eterm wrap_ebif_math_exp_1(Process*, Eterm, UWord *I);
Eterm math_log_1(Process*, Eterm);
Eterm wrap_math_log_1(Process*, Eterm, UWord *I);
Eterm ebif_math_log_1(Process*, Eterm);
Eterm wrap_ebif_math_log_1(Process*, Eterm, UWord *I);
Eterm math_log10_1(Process*, Eterm);
Eterm wrap_math_log10_1(Process*, Eterm, UWord *I);
Eterm ebif_math_log10_1(Process*, Eterm);
Eterm wrap_ebif_math_log10_1(Process*, Eterm, UWord *I);
Eterm math_sqrt_1(Process*, Eterm);
Eterm wrap_math_sqrt_1(Process*, Eterm, UWord *I);
Eterm ebif_math_sqrt_1(Process*, Eterm);
Eterm wrap_ebif_math_sqrt_1(Process*, Eterm, UWord *I);
Eterm math_atan2_2(Process*, Eterm, Eterm);
Eterm wrap_math_atan2_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_math_atan2_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_math_atan2_2(Process*, Eterm, Eterm, UWord *I);
Eterm math_pow_2(Process*, Eterm, Eterm);
Eterm wrap_math_pow_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_math_pow_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_math_pow_2(Process*, Eterm, Eterm, UWord *I);
Eterm start_timer_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_start_timer_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ebif_start_timer_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ebif_start_timer_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm send_after_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_send_after_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ebif_send_after_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ebif_send_after_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm cancel_timer_1(Process*, Eterm);
Eterm wrap_cancel_timer_1(Process*, Eterm, UWord *I);
Eterm ebif_cancel_timer_1(Process*, Eterm);
Eterm wrap_ebif_cancel_timer_1(Process*, Eterm, UWord *I);
Eterm read_timer_1(Process*, Eterm);
Eterm wrap_read_timer_1(Process*, Eterm, UWord *I);
Eterm ebif_read_timer_1(Process*, Eterm);
Eterm wrap_ebif_read_timer_1(Process*, Eterm, UWord *I);
Eterm make_tuple_2(Process*, Eterm, Eterm);
Eterm wrap_make_tuple_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_make_tuple_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_make_tuple_2(Process*, Eterm, Eterm, UWord *I);
Eterm append_element_2(Process*, Eterm, Eterm);
Eterm wrap_append_element_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_append_element_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_append_element_2(Process*, Eterm, Eterm, UWord *I);
Eterm make_tuple_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_make_tuple_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm system_flag_2(Process*, Eterm, Eterm);
Eterm wrap_system_flag_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_system_flag_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_system_flag_2(Process*, Eterm, Eterm, UWord *I);
Eterm system_info_1(Process*, Eterm);
Eterm wrap_system_info_1(Process*, Eterm, UWord *I);
Eterm ebif_system_info_1(Process*, Eterm);
Eterm wrap_ebif_system_info_1(Process*, Eterm, UWord *I);
Eterm system_monitor_0(Process*);
Eterm wrap_system_monitor_0(Process*, UWord *I);
Eterm ebif_system_monitor_0(Process*);
Eterm wrap_ebif_system_monitor_0(Process*, UWord *I);
Eterm system_monitor_1(Process*, Eterm);
Eterm wrap_system_monitor_1(Process*, Eterm, UWord *I);
Eterm ebif_system_monitor_1(Process*, Eterm);
Eterm wrap_ebif_system_monitor_1(Process*, Eterm, UWord *I);
Eterm system_monitor_2(Process*, Eterm, Eterm);
Eterm wrap_system_monitor_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_system_monitor_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_system_monitor_2(Process*, Eterm, Eterm, UWord *I);
Eterm system_profile_2(Process*, Eterm, Eterm);
Eterm wrap_system_profile_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_system_profile_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_system_profile_2(Process*, Eterm, Eterm, UWord *I);
Eterm system_profile_0(Process*);
Eterm wrap_system_profile_0(Process*, UWord *I);
Eterm ebif_system_profile_0(Process*);
Eterm wrap_ebif_system_profile_0(Process*, UWord *I);
Eterm ref_to_list_1(Process*, Eterm);
Eterm wrap_ref_to_list_1(Process*, Eterm, UWord *I);
Eterm ebif_ref_to_string_1(Process*, Eterm);
Eterm wrap_ebif_ref_to_string_1(Process*, Eterm, UWord *I);
Eterm port_to_list_1(Process*, Eterm);
Eterm wrap_port_to_list_1(Process*, Eterm, UWord *I);
Eterm ebif_port_to_string_1(Process*, Eterm);
Eterm wrap_ebif_port_to_string_1(Process*, Eterm, UWord *I);
Eterm fun_to_list_1(Process*, Eterm);
Eterm wrap_fun_to_list_1(Process*, Eterm, UWord *I);
Eterm ebif_fun_to_string_1(Process*, Eterm);
Eterm wrap_ebif_fun_to_string_1(Process*, Eterm, UWord *I);
Eterm monitor_2(Process*, Eterm, Eterm);
Eterm wrap_monitor_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_monitor_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_monitor_2(Process*, Eterm, Eterm, UWord *I);
Eterm demonitor_1(Process*, Eterm);
Eterm wrap_demonitor_1(Process*, Eterm, UWord *I);
Eterm ebif_demonitor_1(Process*, Eterm);
Eterm wrap_ebif_demonitor_1(Process*, Eterm, UWord *I);
Eterm demonitor_2(Process*, Eterm, Eterm);
Eterm wrap_demonitor_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_demonitor_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_demonitor_2(Process*, Eterm, Eterm, UWord *I);
Eterm is_process_alive_1(Process*, Eterm);
Eterm wrap_is_process_alive_1(Process*, Eterm, UWord *I);
Eterm ebif_proc_is_alive_1(Process*, Eterm);
Eterm wrap_ebif_proc_is_alive_1(Process*, Eterm, UWord *I);
Eterm error_1(Process*, Eterm);
Eterm wrap_error_1(Process*, Eterm, UWord *I);
Eterm ebif_error_1(Process*, Eterm);
Eterm wrap_ebif_error_1(Process*, Eterm, UWord *I);
Eterm error_2(Process*, Eterm, Eterm);
Eterm wrap_error_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_error_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_error_2(Process*, Eterm, Eterm, UWord *I);
Eterm raise_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_raise_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ebif_raise_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ebif_raise_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm get_stacktrace_0(Process*);
Eterm wrap_get_stacktrace_0(Process*, UWord *I);
Eterm ebif_get_stacktrace_0(Process*);
Eterm wrap_ebif_get_stacktrace_0(Process*, UWord *I);
Eterm is_builtin_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_is_builtin_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ebif_is_builtin_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ebif_is_builtin_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm and_2(Process*, Eterm, Eterm);
Eterm wrap_and_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_and_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_and_2(Process*, Eterm, Eterm, UWord *I);
Eterm or_2(Process*, Eterm, Eterm);
Eterm wrap_or_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_or_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_or_2(Process*, Eterm, Eterm, UWord *I);
Eterm xor_2(Process*, Eterm, Eterm);
Eterm wrap_xor_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_xor_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_xor_2(Process*, Eterm, Eterm, UWord *I);
Eterm not_1(Process*, Eterm);
Eterm wrap_not_1(Process*, Eterm, UWord *I);
Eterm ebif_not_1(Process*, Eterm);
Eterm wrap_ebif_not_1(Process*, Eterm, UWord *I);
Eterm sgt_2(Process*, Eterm, Eterm);
Eterm wrap_sgt_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_gt_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_gt_2(Process*, Eterm, Eterm, UWord *I);
Eterm sge_2(Process*, Eterm, Eterm);
Eterm wrap_sge_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_ge_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_ge_2(Process*, Eterm, Eterm, UWord *I);
Eterm slt_2(Process*, Eterm, Eterm);
Eterm wrap_slt_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_lt_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_lt_2(Process*, Eterm, Eterm, UWord *I);
Eterm sle_2(Process*, Eterm, Eterm);
Eterm wrap_sle_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_le_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_le_2(Process*, Eterm, Eterm, UWord *I);
Eterm seq_2(Process*, Eterm, Eterm);
Eterm wrap_seq_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_eq_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_eq_2(Process*, Eterm, Eterm, UWord *I);
Eterm seqeq_2(Process*, Eterm, Eterm);
Eterm wrap_seqeq_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_areq_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_areq_2(Process*, Eterm, Eterm, UWord *I);
Eterm sneq_2(Process*, Eterm, Eterm);
Eterm wrap_sneq_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_neq_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_neq_2(Process*, Eterm, Eterm, UWord *I);
Eterm sneqeq_2(Process*, Eterm, Eterm);
Eterm wrap_sneqeq_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_nareq_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_nareq_2(Process*, Eterm, Eterm, UWord *I);
Eterm splus_2(Process*, Eterm, Eterm);
Eterm wrap_splus_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_plus_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_plus_2(Process*, Eterm, Eterm, UWord *I);
Eterm sminus_2(Process*, Eterm, Eterm);
Eterm wrap_sminus_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_minus_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_minus_2(Process*, Eterm, Eterm, UWord *I);
Eterm stimes_2(Process*, Eterm, Eterm);
Eterm wrap_stimes_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_multiply_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_multiply_2(Process*, Eterm, Eterm, UWord *I);
Eterm div_2(Process*, Eterm, Eterm);
Eterm wrap_div_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_divide_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_divide_2(Process*, Eterm, Eterm, UWord *I);
Eterm intdiv_2(Process*, Eterm, Eterm);
Eterm wrap_intdiv_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_intdiv_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_intdiv_2(Process*, Eterm, Eterm, UWord *I);
Eterm rem_2(Process*, Eterm, Eterm);
Eterm wrap_rem_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_rem_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_rem_2(Process*, Eterm, Eterm, UWord *I);
Eterm bor_2(Process*, Eterm, Eterm);
Eterm wrap_bor_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_bor_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_bor_2(Process*, Eterm, Eterm, UWord *I);
Eterm band_2(Process*, Eterm, Eterm);
Eterm wrap_band_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_band_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_band_2(Process*, Eterm, Eterm, UWord *I);
Eterm bxor_2(Process*, Eterm, Eterm);
Eterm wrap_bxor_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_bxor_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_bxor_2(Process*, Eterm, Eterm, UWord *I);
Eterm bsl_2(Process*, Eterm, Eterm);
Eterm wrap_bsl_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_bsl_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_bsl_2(Process*, Eterm, Eterm, UWord *I);
Eterm bsr_2(Process*, Eterm, Eterm);
Eterm wrap_bsr_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_bsr_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_bsr_2(Process*, Eterm, Eterm, UWord *I);
Eterm bnot_1(Process*, Eterm);
Eterm wrap_bnot_1(Process*, Eterm, UWord *I);
Eterm ebif_bnot_1(Process*, Eterm);
Eterm wrap_ebif_bnot_1(Process*, Eterm, UWord *I);
Eterm sminus_1(Process*, Eterm);
Eterm wrap_sminus_1(Process*, Eterm, UWord *I);
Eterm ebif_minus_1(Process*, Eterm);
Eterm wrap_ebif_minus_1(Process*, Eterm, UWord *I);
Eterm splus_1(Process*, Eterm);
Eterm wrap_splus_1(Process*, Eterm, UWord *I);
Eterm ebif_plus_1(Process*, Eterm);
Eterm wrap_ebif_plus_1(Process*, Eterm, UWord *I);
Eterm ebif_bang_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_bang_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_send_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_send_2(Process*, Eterm, Eterm, UWord *I);
Eterm send_2(Process*, Eterm, Eterm);
Eterm wrap_send_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_send_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ebif_send_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm send_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_send_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ebif_plusplus_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_plusplus_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_append_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_append_2(Process*, Eterm, Eterm, UWord *I);
Eterm append_2(Process*, Eterm, Eterm);
Eterm wrap_append_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_minusminus_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_minusminus_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_list_subtract_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_list_subtract_2(Process*, Eterm, Eterm, UWord *I);
Eterm subtract_2(Process*, Eterm, Eterm);
Eterm wrap_subtract_2(Process*, Eterm, Eterm, UWord *I);
Eterm is_atom_1(Process*, Eterm);
Eterm wrap_is_atom_1(Process*, Eterm, UWord *I);
Eterm ebif_is_atom_1(Process*, Eterm);
Eterm wrap_ebif_is_atom_1(Process*, Eterm, UWord *I);
Eterm is_list_1(Process*, Eterm);
Eterm wrap_is_list_1(Process*, Eterm, UWord *I);
Eterm ebif_is_list_1(Process*, Eterm);
Eterm wrap_ebif_is_list_1(Process*, Eterm, UWord *I);
Eterm is_tuple_1(Process*, Eterm);
Eterm wrap_is_tuple_1(Process*, Eterm, UWord *I);
Eterm ebif_is_tuple_1(Process*, Eterm);
Eterm wrap_ebif_is_tuple_1(Process*, Eterm, UWord *I);
Eterm is_float_1(Process*, Eterm);
Eterm wrap_is_float_1(Process*, Eterm, UWord *I);
Eterm ebif_is_float_1(Process*, Eterm);
Eterm wrap_ebif_is_float_1(Process*, Eterm, UWord *I);
Eterm is_integer_1(Process*, Eterm);
Eterm wrap_is_integer_1(Process*, Eterm, UWord *I);
Eterm ebif_is_integer_1(Process*, Eterm);
Eterm wrap_ebif_is_integer_1(Process*, Eterm, UWord *I);
Eterm is_number_1(Process*, Eterm);
Eterm wrap_is_number_1(Process*, Eterm, UWord *I);
Eterm ebif_is_number_1(Process*, Eterm);
Eterm wrap_ebif_is_number_1(Process*, Eterm, UWord *I);
Eterm is_pid_1(Process*, Eterm);
Eterm wrap_is_pid_1(Process*, Eterm, UWord *I);
Eterm ebif_is_pid_1(Process*, Eterm);
Eterm wrap_ebif_is_pid_1(Process*, Eterm, UWord *I);
Eterm is_port_1(Process*, Eterm);
Eterm wrap_is_port_1(Process*, Eterm, UWord *I);
Eterm ebif_is_port_1(Process*, Eterm);
Eterm wrap_ebif_is_port_1(Process*, Eterm, UWord *I);
Eterm is_reference_1(Process*, Eterm);
Eterm wrap_is_reference_1(Process*, Eterm, UWord *I);
Eterm ebif_is_reference_1(Process*, Eterm);
Eterm wrap_ebif_is_reference_1(Process*, Eterm, UWord *I);
Eterm is_binary_1(Process*, Eterm);
Eterm wrap_is_binary_1(Process*, Eterm, UWord *I);
Eterm ebif_is_binary_1(Process*, Eterm);
Eterm wrap_ebif_is_binary_1(Process*, Eterm, UWord *I);
Eterm is_function_1(Process*, Eterm);
Eterm wrap_is_function_1(Process*, Eterm, UWord *I);
Eterm ebif_is_function_1(Process*, Eterm);
Eterm wrap_ebif_is_function_1(Process*, Eterm, UWord *I);
Eterm is_function_2(Process*, Eterm, Eterm);
Eterm wrap_is_function_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_is_function_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_is_function_2(Process*, Eterm, Eterm, UWord *I);
Eterm is_record_2(Process*, Eterm, Eterm);
Eterm wrap_is_record_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_is_record_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_is_record_2(Process*, Eterm, Eterm, UWord *I);
Eterm is_record_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_is_record_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ebif_is_record_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ebif_is_record_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm match_spec_test_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_match_spec_test_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ets_all_0(Process*);
Eterm wrap_ets_all_0(Process*, UWord *I);
Eterm ebif_ets_all_0(Process*);
Eterm wrap_ebif_ets_all_0(Process*, UWord *I);
Eterm ets_new_2(Process*, Eterm, Eterm);
Eterm wrap_ets_new_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_ets_new_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_ets_new_2(Process*, Eterm, Eterm, UWord *I);
Eterm ets_delete_1(Process*, Eterm);
Eterm wrap_ets_delete_1(Process*, Eterm, UWord *I);
Eterm ebif_ets_delete_1(Process*, Eterm);
Eterm wrap_ebif_ets_delete_1(Process*, Eterm, UWord *I);
Eterm ets_delete_2(Process*, Eterm, Eterm);
Eterm wrap_ets_delete_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_ets_delete_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_ets_delete_2(Process*, Eterm, Eterm, UWord *I);
Eterm ets_delete_all_objects_1(Process*, Eterm);
Eterm wrap_ets_delete_all_objects_1(Process*, Eterm, UWord *I);
Eterm ebif_ets_delete_all_objects_1(Process*, Eterm);
Eterm wrap_ebif_ets_delete_all_objects_1(Process*, Eterm, UWord *I);
Eterm ets_delete_object_2(Process*, Eterm, Eterm);
Eterm wrap_ets_delete_object_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_ets_delete_object_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_ets_delete_object_2(Process*, Eterm, Eterm, UWord *I);
Eterm ets_first_1(Process*, Eterm);
Eterm wrap_ets_first_1(Process*, Eterm, UWord *I);
Eterm ebif_ets_first_1(Process*, Eterm);
Eterm wrap_ebif_ets_first_1(Process*, Eterm, UWord *I);
Eterm ets_is_compiled_ms_1(Process*, Eterm);
Eterm wrap_ets_is_compiled_ms_1(Process*, Eterm, UWord *I);
Eterm ebif_ets_is_compiled_ms_1(Process*, Eterm);
Eterm wrap_ebif_ets_is_compiled_ms_1(Process*, Eterm, UWord *I);
Eterm ets_lookup_2(Process*, Eterm, Eterm);
Eterm wrap_ets_lookup_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_ets_lookup_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_ets_lookup_2(Process*, Eterm, Eterm, UWord *I);
Eterm ets_lookup_element_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ets_lookup_element_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ebif_ets_lookup_element_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ebif_ets_lookup_element_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ets_info_1(Process*, Eterm);
Eterm wrap_ets_info_1(Process*, Eterm, UWord *I);
Eterm ebif_ets_info_1(Process*, Eterm);
Eterm wrap_ebif_ets_info_1(Process*, Eterm, UWord *I);
Eterm ets_info_2(Process*, Eterm, Eterm);
Eterm wrap_ets_info_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_ets_info_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_ets_info_2(Process*, Eterm, Eterm, UWord *I);
Eterm ets_last_1(Process*, Eterm);
Eterm wrap_ets_last_1(Process*, Eterm, UWord *I);
Eterm ebif_ets_last_1(Process*, Eterm);
Eterm wrap_ebif_ets_last_1(Process*, Eterm, UWord *I);
Eterm ets_match_1(Process*, Eterm);
Eterm wrap_ets_match_1(Process*, Eterm, UWord *I);
Eterm ebif_ets_match_1(Process*, Eterm);
Eterm wrap_ebif_ets_match_1(Process*, Eterm, UWord *I);
Eterm ets_match_2(Process*, Eterm, Eterm);
Eterm wrap_ets_match_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_ets_match_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_ets_match_2(Process*, Eterm, Eterm, UWord *I);
Eterm ets_match_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ets_match_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ebif_ets_match_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ebif_ets_match_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ets_match_object_1(Process*, Eterm);
Eterm wrap_ets_match_object_1(Process*, Eterm, UWord *I);
Eterm ebif_ets_match_object_1(Process*, Eterm);
Eterm wrap_ebif_ets_match_object_1(Process*, Eterm, UWord *I);
Eterm ets_match_object_2(Process*, Eterm, Eterm);
Eterm wrap_ets_match_object_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_ets_match_object_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_ets_match_object_2(Process*, Eterm, Eterm, UWord *I);
Eterm ets_match_object_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ets_match_object_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ebif_ets_match_object_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ebif_ets_match_object_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ets_member_2(Process*, Eterm, Eterm);
Eterm wrap_ets_member_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_ets_member_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_ets_member_2(Process*, Eterm, Eterm, UWord *I);
Eterm ets_next_2(Process*, Eterm, Eterm);
Eterm wrap_ets_next_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_ets_next_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_ets_next_2(Process*, Eterm, Eterm, UWord *I);
Eterm ets_prev_2(Process*, Eterm, Eterm);
Eterm wrap_ets_prev_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_ets_prev_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_ets_prev_2(Process*, Eterm, Eterm, UWord *I);
Eterm ets_insert_2(Process*, Eterm, Eterm);
Eterm wrap_ets_insert_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_ets_insert_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_ets_insert_2(Process*, Eterm, Eterm, UWord *I);
Eterm ets_insert_new_2(Process*, Eterm, Eterm);
Eterm wrap_ets_insert_new_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_ets_insert_new_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_ets_insert_new_2(Process*, Eterm, Eterm, UWord *I);
Eterm ets_rename_2(Process*, Eterm, Eterm);
Eterm wrap_ets_rename_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_ets_rename_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_ets_rename_2(Process*, Eterm, Eterm, UWord *I);
Eterm ets_safe_fixtable_2(Process*, Eterm, Eterm);
Eterm wrap_ets_safe_fixtable_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_ets_safe_fixtable_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_ets_safe_fixtable_2(Process*, Eterm, Eterm, UWord *I);
Eterm ets_slot_2(Process*, Eterm, Eterm);
Eterm wrap_ets_slot_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_ets_slot_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_ets_slot_2(Process*, Eterm, Eterm, UWord *I);
Eterm ets_update_counter_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ets_update_counter_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ebif_ets_update_counter_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ebif_ets_update_counter_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ets_select_1(Process*, Eterm);
Eterm wrap_ets_select_1(Process*, Eterm, UWord *I);
Eterm ebif_ets_select_1(Process*, Eterm);
Eterm wrap_ebif_ets_select_1(Process*, Eterm, UWord *I);
Eterm ets_select_2(Process*, Eterm, Eterm);
Eterm wrap_ets_select_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_ets_select_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_ets_select_2(Process*, Eterm, Eterm, UWord *I);
Eterm ets_select_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ets_select_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ebif_ets_select_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ebif_ets_select_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ets_select_count_2(Process*, Eterm, Eterm);
Eterm wrap_ets_select_count_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_ets_select_count_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_ets_select_count_2(Process*, Eterm, Eterm, UWord *I);
Eterm ets_select_reverse_1(Process*, Eterm);
Eterm wrap_ets_select_reverse_1(Process*, Eterm, UWord *I);
Eterm ebif_ets_select_reverse_1(Process*, Eterm);
Eterm wrap_ebif_ets_select_reverse_1(Process*, Eterm, UWord *I);
Eterm ets_select_reverse_2(Process*, Eterm, Eterm);
Eterm wrap_ets_select_reverse_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_ets_select_reverse_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_ets_select_reverse_2(Process*, Eterm, Eterm, UWord *I);
Eterm ets_select_reverse_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ets_select_reverse_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ebif_ets_select_reverse_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ebif_ets_select_reverse_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ets_select_delete_2(Process*, Eterm, Eterm);
Eterm wrap_ets_select_delete_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_ets_select_delete_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_ets_select_delete_2(Process*, Eterm, Eterm, UWord *I);
Eterm ets_match_spec_compile_1(Process*, Eterm);
Eterm wrap_ets_match_spec_compile_1(Process*, Eterm, UWord *I);
Eterm ebif_ets_match_spec_compile_1(Process*, Eterm);
Eterm wrap_ebif_ets_match_spec_compile_1(Process*, Eterm, UWord *I);
Eterm ets_match_spec_run_r_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ets_match_spec_run_r_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ebif_ets_match_spec_run_r_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ebif_ets_match_spec_run_r_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm os_putenv_2(Process*, Eterm, Eterm);
Eterm wrap_os_putenv_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_os_setenv_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_os_setenv_2(Process*, Eterm, Eterm, UWord *I);
Eterm os_getenv_0(Process*);
Eterm wrap_os_getenv_0(Process*, UWord *I);
Eterm ebif_os_getenv_0(Process*);
Eterm wrap_ebif_os_getenv_0(Process*, UWord *I);
Eterm os_getenv_1(Process*, Eterm);
Eterm wrap_os_getenv_1(Process*, Eterm, UWord *I);
Eterm ebif_os_getenv_1(Process*, Eterm);
Eterm wrap_ebif_os_getenv_1(Process*, Eterm, UWord *I);
Eterm os_getpid_0(Process*);
Eterm wrap_os_getpid_0(Process*, UWord *I);
Eterm ebif_os_pid_0(Process*);
Eterm wrap_ebif_os_pid_0(Process*, UWord *I);
Eterm os_timestamp_0(Process*);
Eterm wrap_os_timestamp_0(Process*, UWord *I);
Eterm ebif_os_timestamp_0(Process*);
Eterm wrap_ebif_os_timestamp_0(Process*, UWord *I);
Eterm erl_ddll_try_load_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_erl_ddll_try_load_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm erl_ddll_try_unload_2(Process*, Eterm, Eterm);
Eterm wrap_erl_ddll_try_unload_2(Process*, Eterm, Eterm, UWord *I);
Eterm erl_ddll_loaded_drivers_0(Process*);
Eterm wrap_erl_ddll_loaded_drivers_0(Process*, UWord *I);
Eterm erl_ddll_info_2(Process*, Eterm, Eterm);
Eterm wrap_erl_ddll_info_2(Process*, Eterm, Eterm, UWord *I);
Eterm erl_ddll_format_error_int_1(Process*, Eterm);
Eterm wrap_erl_ddll_format_error_int_1(Process*, Eterm, UWord *I);
Eterm erl_ddll_monitor_2(Process*, Eterm, Eterm);
Eterm wrap_erl_ddll_monitor_2(Process*, Eterm, Eterm, UWord *I);
Eterm erl_ddll_demonitor_1(Process*, Eterm);
Eterm wrap_erl_ddll_demonitor_1(Process*, Eterm, UWord *I);
Eterm re_compile_1(Process*, Eterm);
Eterm wrap_re_compile_1(Process*, Eterm, UWord *I);
Eterm re_compile_2(Process*, Eterm, Eterm);
Eterm wrap_re_compile_2(Process*, Eterm, Eterm, UWord *I);
Eterm re_run_2(Process*, Eterm, Eterm);
Eterm wrap_re_run_2(Process*, Eterm, Eterm, UWord *I);
Eterm re_run_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_re_run_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm lists_member_2(Process*, Eterm, Eterm);
Eterm wrap_lists_member_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_list_is_element_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_list_is_element_2(Process*, Eterm, Eterm, UWord *I);
Eterm lists_reverse_2(Process*, Eterm, Eterm);
Eterm wrap_lists_reverse_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_list_reverse_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_list_reverse_2(Process*, Eterm, Eterm, UWord *I);
Eterm lists_keymember_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_lists_keymember_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ebif_keylist_is_element_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ebif_keylist_is_element_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm lists_keysearch_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_lists_keysearch_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ebif_keylist_search_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ebif_keylist_search_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm lists_keyfind_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_lists_keyfind_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm erts_debug_disassemble_1(Process*, Eterm);
Eterm wrap_erts_debug_disassemble_1(Process*, Eterm, UWord *I);
Eterm ebif_erts_debug_disassemble_1(Process*, Eterm);
Eterm wrap_ebif_erts_debug_disassemble_1(Process*, Eterm, UWord *I);
Eterm erts_debug_breakpoint_2(Process*, Eterm, Eterm);
Eterm wrap_erts_debug_breakpoint_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_erts_debug_breakpoint_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_erts_debug_breakpoint_2(Process*, Eterm, Eterm, UWord *I);
Eterm erts_debug_same_2(Process*, Eterm, Eterm);
Eterm wrap_erts_debug_same_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_erts_debug_same_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_erts_debug_same_2(Process*, Eterm, Eterm, UWord *I);
Eterm erts_debug_flat_size_1(Process*, Eterm);
Eterm wrap_erts_debug_flat_size_1(Process*, Eterm, UWord *I);
Eterm ebif_erts_debug_flat_size_1(Process*, Eterm);
Eterm wrap_ebif_erts_debug_flat_size_1(Process*, Eterm, UWord *I);
Eterm erts_debug_get_internal_state_1(Process*, Eterm);
Eterm wrap_erts_debug_get_internal_state_1(Process*, Eterm, UWord *I);
Eterm ebif_erts_debug_get_internal_state_1(Process*, Eterm);
Eterm wrap_ebif_erts_debug_get_internal_state_1(Process*, Eterm, UWord *I);
Eterm erts_debug_set_internal_state_2(Process*, Eterm, Eterm);
Eterm wrap_erts_debug_set_internal_state_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_erts_debug_set_internal_state_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_erts_debug_set_internal_state_2(Process*, Eterm, Eterm, UWord *I);
Eterm erts_debug_display_1(Process*, Eterm);
Eterm wrap_erts_debug_display_1(Process*, Eterm, UWord *I);
Eterm ebif_erts_debug_display_1(Process*, Eterm);
Eterm wrap_ebif_erts_debug_display_1(Process*, Eterm, UWord *I);
Eterm erts_debug_dist_ext_to_term_2(Process*, Eterm, Eterm);
Eterm wrap_erts_debug_dist_ext_to_term_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_erts_debug_dist_ext_to_term_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_erts_debug_dist_ext_to_term_2(Process*, Eterm, Eterm, UWord *I);
Eterm erts_debug_dump_monitors_1(Process*, Eterm);
Eterm wrap_erts_debug_dump_monitors_1(Process*, Eterm, UWord *I);
Eterm erts_debug_dump_links_1(Process*, Eterm);
Eterm wrap_erts_debug_dump_links_1(Process*, Eterm, UWord *I);
Eterm erts_debug_lock_counters_1(Process*, Eterm);
Eterm wrap_erts_debug_lock_counters_1(Process*, Eterm, UWord *I);
Eterm code_get_chunk_2(Process*, Eterm, Eterm);
Eterm wrap_code_get_chunk_2(Process*, Eterm, Eterm, UWord *I);
Eterm ebif_code_get_chunk_2(Process*, Eterm, Eterm);
Eterm wrap_ebif_code_get_chunk_2(Process*, Eterm, Eterm, UWord *I);
Eterm code_module_md5_1(Process*, Eterm);
Eterm wrap_code_module_md5_1(Process*, Eterm, UWord *I);
Eterm ebif_code_module_md5_1(Process*, Eterm);
Eterm wrap_ebif_code_module_md5_1(Process*, Eterm, UWord *I);
Eterm code_make_stub_module_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_code_make_stub_module_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ebif_code_make_stub_module_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ebif_code_make_stub_module_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm code_is_module_native_1(Process*, Eterm);
Eterm wrap_code_is_module_native_1(Process*, Eterm, UWord *I);
Eterm ebif_code_is_native_1(Process*, Eterm);
Eterm wrap_ebif_code_is_native_1(Process*, Eterm, UWord *I);
Eterm hibernate_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_hibernate_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm error_logger_warning_map_0(Process*);
Eterm wrap_error_logger_warning_map_0(Process*, UWord *I);
Eterm get_module_info_1(Process*, Eterm);
Eterm wrap_get_module_info_1(Process*, Eterm, UWord *I);
Eterm get_module_info_2(Process*, Eterm, Eterm);
Eterm wrap_get_module_info_2(Process*, Eterm, Eterm, UWord *I);
Eterm is_boolean_1(Process*, Eterm);
Eterm wrap_is_boolean_1(Process*, Eterm, UWord *I);
Eterm string_to_integer_1(Process*, Eterm);
Eterm wrap_string_to_integer_1(Process*, Eterm, UWord *I);
Eterm string_to_float_1(Process*, Eterm);
Eterm wrap_string_to_float_1(Process*, Eterm, UWord *I);
Eterm make_fun_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_make_fun_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm iolist_size_1(Process*, Eterm);
Eterm wrap_iolist_size_1(Process*, Eterm, UWord *I);
Eterm iolist_to_binary_1(Process*, Eterm);
Eterm wrap_iolist_to_binary_1(Process*, Eterm, UWord *I);
Eterm list_to_existing_atom_1(Process*, Eterm);
Eterm wrap_list_to_existing_atom_1(Process*, Eterm, UWord *I);
Eterm is_bitstring_1(Process*, Eterm);
Eterm wrap_is_bitstring_1(Process*, Eterm, UWord *I);
Eterm tuple_size_1(Process*, Eterm);
Eterm wrap_tuple_size_1(Process*, Eterm, UWord *I);
Eterm byte_size_1(Process*, Eterm);
Eterm wrap_byte_size_1(Process*, Eterm, UWord *I);
Eterm bit_size_1(Process*, Eterm);
Eterm wrap_bit_size_1(Process*, Eterm, UWord *I);
Eterm list_to_bitstring_1(Process*, Eterm);
Eterm wrap_list_to_bitstring_1(Process*, Eterm, UWord *I);
Eterm bitstring_to_list_1(Process*, Eterm);
Eterm wrap_bitstring_to_list_1(Process*, Eterm, UWord *I);
Eterm ets_update_element_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ets_update_element_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm decode_packet_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_decode_packet_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm unicode_characters_to_binary_2(Process*, Eterm, Eterm);
Eterm wrap_unicode_characters_to_binary_2(Process*, Eterm, Eterm, UWord *I);
Eterm unicode_characters_to_list_2(Process*, Eterm, Eterm);
Eterm wrap_unicode_characters_to_list_2(Process*, Eterm, Eterm, UWord *I);
Eterm unicode_bin_is_7bit_1(Process*, Eterm);
Eterm wrap_unicode_bin_is_7bit_1(Process*, Eterm, UWord *I);
Eterm atom_to_binary_2(Process*, Eterm, Eterm);
Eterm wrap_atom_to_binary_2(Process*, Eterm, Eterm, UWord *I);
Eterm binary_to_atom_2(Process*, Eterm, Eterm);
Eterm wrap_binary_to_atom_2(Process*, Eterm, Eterm, UWord *I);
Eterm binary_to_existing_atom_2(Process*, Eterm, Eterm);
Eterm wrap_binary_to_existing_atom_2(Process*, Eterm, Eterm, UWord *I);
Eterm net_kernel_dflag_unicode_io_1(Process*, Eterm);
Eterm wrap_net_kernel_dflag_unicode_io_1(Process*, Eterm, UWord *I);
Eterm ets_give_away_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_ets_give_away_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm ets_setopts_2(Process*, Eterm, Eterm);
Eterm wrap_ets_setopts_2(Process*, Eterm, Eterm, UWord *I);
Eterm load_nif_2(Process*, Eterm, Eterm);
Eterm wrap_load_nif_2(Process*, Eterm, Eterm, UWord *I);
Eterm call_on_load_function_1(Process*, Eterm);
Eterm wrap_call_on_load_function_1(Process*, Eterm, UWord *I);
Eterm finish_after_on_load_2(Process*, Eterm, Eterm);
Eterm wrap_finish_after_on_load_2(Process*, Eterm, Eterm, UWord *I);
Eterm binary_to_term_2(Process*, Eterm, Eterm);
Eterm wrap_binary_to_term_2(Process*, Eterm, Eterm, UWord *I);
Eterm binary_part_2(Process*, Eterm, Eterm);
Eterm wrap_binary_part_2(Process*, Eterm, Eterm, UWord *I);
Eterm binary_part_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_binary_part_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm binary_compile_pattern_1(Process*, Eterm);
Eterm wrap_binary_compile_pattern_1(Process*, Eterm, UWord *I);
Eterm binary_match_2(Process*, Eterm, Eterm);
Eterm wrap_binary_match_2(Process*, Eterm, Eterm, UWord *I);
Eterm binary_match_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_binary_match_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm binary_matches_2(Process*, Eterm, Eterm);
Eterm wrap_binary_matches_2(Process*, Eterm, Eterm, UWord *I);
Eterm binary_matches_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_binary_matches_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm binary_longest_common_prefix_1(Process*, Eterm);
Eterm wrap_binary_longest_common_prefix_1(Process*, Eterm, UWord *I);
Eterm binary_longest_common_suffix_1(Process*, Eterm);
Eterm wrap_binary_longest_common_suffix_1(Process*, Eterm, UWord *I);
Eterm binary_first_1(Process*, Eterm);
Eterm wrap_binary_first_1(Process*, Eterm, UWord *I);
Eterm binary_last_1(Process*, Eterm);
Eterm wrap_binary_last_1(Process*, Eterm, UWord *I);
Eterm binary_at_2(Process*, Eterm, Eterm);
Eterm wrap_binary_at_2(Process*, Eterm, Eterm, UWord *I);
Eterm binary_binary_part_2(Process*, Eterm, Eterm);
Eterm wrap_binary_binary_part_2(Process*, Eterm, Eterm, UWord *I);
Eterm binary_binary_part_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_binary_binary_part_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm binary_bin_to_list_1(Process*, Eterm);
Eterm wrap_binary_bin_to_list_1(Process*, Eterm, UWord *I);
Eterm binary_bin_to_list_2(Process*, Eterm, Eterm);
Eterm wrap_binary_bin_to_list_2(Process*, Eterm, Eterm, UWord *I);
Eterm binary_bin_to_list_3(Process*, Eterm, Eterm, Eterm);
Eterm wrap_binary_bin_to_list_3(Process*, Eterm, Eterm, Eterm, UWord *I);
Eterm binary_list_to_bin_1(Process*, Eterm);
Eterm wrap_binary_list_to_bin_1(Process*, Eterm, UWord *I);
Eterm binary_copy_1(Process*, Eterm);
Eterm wrap_binary_copy_1(Process*, Eterm, UWord *I);
Eterm binary_copy_2(Process*, Eterm, Eterm);
Eterm wrap_binary_copy_2(Process*, Eterm, Eterm, UWord *I);
Eterm binary_referenced_byte_size_1(Process*, Eterm);
Eterm wrap_binary_referenced_byte_size_1(Process*, Eterm, UWord *I);
Eterm binary_encode_unsigned_1(Process*, Eterm);
Eterm wrap_binary_encode_unsigned_1(Process*, Eterm, UWord *I);
Eterm binary_encode_unsigned_2(Process*, Eterm, Eterm);
Eterm wrap_binary_encode_unsigned_2(Process*, Eterm, Eterm, UWord *I);
Eterm binary_decode_unsigned_1(Process*, Eterm);
Eterm wrap_binary_decode_unsigned_1(Process*, Eterm, UWord *I);
Eterm binary_decode_unsigned_2(Process*, Eterm, Eterm);
Eterm wrap_binary_decode_unsigned_2(Process*, Eterm, Eterm, UWord *I);
Eterm nif_error_1(Process*, Eterm);
Eterm wrap_nif_error_1(Process*, Eterm, UWord *I);
Eterm nif_error_2(Process*, Eterm, Eterm);
Eterm wrap_nif_error_2(Process*, Eterm, Eterm, UWord *I);
Eterm hash_2(Process*, Eterm, Eterm);
Eterm wrap_hash_2(Process*, Eterm, Eterm, UWord *I);
#endif
