/*
 *  Warning: Do not edit this file.  It was automatically
 *  generated by 'make_tables' on Mon Sep 13 15:06:40 2010.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif /* HAVE_CONFIG_H */
#include "export.h"
#include "sys.h"
#include "erl_vm.h"
#include "global.h"
#include "erl_process.h"
#include "bif.h"
#include "erl_bif_table.h"
#include "erl_atom_table.h"

Eterm
ebif_abs_1(Process* p, Eterm arg1)
{
    return abs_1(p, arg1);
}

Eterm
ebif_adler32_1(Process* p, Eterm arg1)
{
    return adler32_1(p, arg1);
}

Eterm
ebif_adler32_2(Process* p, Eterm arg1, Eterm arg2)
{
    return adler32_2(p, arg1, arg2);
}

Eterm
ebif_adler32_combine_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3)
{
    return adler32_combine_3(p, arg1, arg2, arg3);
}

Eterm
ebif_apply_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3)
{
    return apply_3(p, arg1, arg2, arg3);
}

Eterm
ebif_atom_to_string_1(Process* p, Eterm arg1)
{
    return atom_to_list_1(p, arg1);
}

Eterm
ebif_binary_to_list_1(Process* p, Eterm arg1)
{
    return binary_to_list_1(p, arg1);
}

Eterm
ebif_binary_to_list_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3)
{
    return binary_to_list_3(p, arg1, arg2, arg3);
}

Eterm
ebif_binary_to_term_1(Process* p, Eterm arg1)
{
    return binary_to_term_1(p, arg1);
}

Eterm
ebif_check_process_code_2(Process* p, Eterm arg1, Eterm arg2)
{
    return check_process_code_2(p, arg1, arg2);
}

Eterm
ebif_crc32_1(Process* p, Eterm arg1)
{
    return crc32_1(p, arg1);
}

Eterm
ebif_crc32_2(Process* p, Eterm arg1, Eterm arg2)
{
    return crc32_2(p, arg1, arg2);
}

Eterm
ebif_crc32_combine_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3)
{
    return crc32_combine_3(p, arg1, arg2, arg3);
}

Eterm
ebif_date_0(Process* p)
{
    return date_0(p);
}

Eterm
ebif_delete_module_1(Process* p, Eterm arg1)
{
    return delete_module_1(p, arg1);
}

Eterm
ebif_display_1(Process* p, Eterm arg1)
{
    return display_1(p, arg1);
}

Eterm
ebif_display_string_1(Process* p, Eterm arg1)
{
    return display_string_1(p, arg1);
}

Eterm
ebif_display_nl_0(Process* p)
{
    return display_nl_0(p);
}

Eterm
ebif_element_2(Process* p, Eterm arg1, Eterm arg2)
{
    return element_2(p, arg1, arg2);
}

Eterm
ebif_erase_0(Process* p)
{
    return erase_0(p);
}

Eterm
ebif_erase_1(Process* p, Eterm arg1)
{
    return erase_1(p, arg1);
}

Eterm
ebif_exit_1(Process* p, Eterm arg1)
{
    return exit_1(p, arg1);
}

Eterm
ebif_signal_2(Process* p, Eterm arg1, Eterm arg2)
{
    return exit_2(p, arg1, arg2);
}

Eterm
ebif_external_size_1(Process* p, Eterm arg1)
{
    return external_size_1(p, arg1);
}

Eterm
ebif_to_float_1(Process* p, Eterm arg1)
{
    return float_1(p, arg1);
}

Eterm
ebif_float_to_string_1(Process* p, Eterm arg1)
{
    return float_to_list_1(p, arg1);
}

Eterm
ebif_fun_info_2(Process* p, Eterm arg1, Eterm arg2)
{
    return fun_info_2(p, arg1, arg2);
}

Eterm
ebif_garbage_collect_0(Process* p)
{
    return garbage_collect_0(p);
}

Eterm
ebif_garbage_collect_1(Process* p, Eterm arg1)
{
    return garbage_collect_1(p, arg1);
}

Eterm
ebif_garbage_collect_message_area_0(Process* p)
{
    return garbage_collect_message_area_0(p);
}

Eterm
ebif_get_0(Process* p)
{
    return get_0(p);
}

Eterm
ebif_get_1(Process* p, Eterm arg1)
{
    return get_1(p, arg1);
}

Eterm
ebif_get_keys_1(Process* p, Eterm arg1)
{
    return get_keys_1(p, arg1);
}

Eterm
ebif_group_leader_0(Process* p)
{
    return group_leader_0(p);
}

Eterm
ebif_group_leader_2(Process* p, Eterm arg1, Eterm arg2)
{
    return group_leader_2(p, arg1, arg2);
}

Eterm
ebif_halt_0(Process* p)
{
    return halt_0(p);
}

Eterm
ebif_halt_1(Process* p, Eterm arg1)
{
    return halt_1(p, arg1);
}

Eterm
ebif_phash2_1(Process* p, Eterm arg1)
{
    return phash2_1(p, arg1);
}

Eterm
ebif_phash2_2(Process* p, Eterm arg1, Eterm arg2)
{
    return phash2_2(p, arg1, arg2);
}

Eterm
ebif_hd_1(Process* p, Eterm arg1)
{
    return hd_1(p, arg1);
}

Eterm
ebif_integer_to_string_1(Process* p, Eterm arg1)
{
    return integer_to_list_1(p, arg1);
}

Eterm
ebif_is_alive_0(Process* p)
{
    return is_alive_0(p);
}

Eterm
ebif_length_1(Process* p, Eterm arg1)
{
    return length_1(p, arg1);
}

Eterm
ebif_link_1(Process* p, Eterm arg1)
{
    return link_1(p, arg1);
}

Eterm
ebif_string_to_atom_1(Process* p, Eterm arg1)
{
    return list_to_atom_1(p, arg1);
}

Eterm
ebif_list_to_binary_1(Process* p, Eterm arg1)
{
    return list_to_binary_1(p, arg1);
}

Eterm
ebif_string_to_float_1(Process* p, Eterm arg1)
{
    return list_to_float_1(p, arg1);
}

Eterm
ebif_string_to_integer_1(Process* p, Eterm arg1)
{
    return list_to_integer_1(p, arg1);
}

Eterm
ebif_string_to_pid_1(Process* p, Eterm arg1)
{
    return list_to_pid_1(p, arg1);
}

Eterm
ebif_list_to_tuple_1(Process* p, Eterm arg1)
{
    return list_to_tuple_1(p, arg1);
}

Eterm
ebif_load_module_2(Process* p, Eterm arg1, Eterm arg2)
{
    return load_module_2(p, arg1, arg2);
}

Eterm
ebif_loaded_0(Process* p)
{
    return loaded_0(p);
}

Eterm
ebif_localtime_0(Process* p)
{
    return localtime_0(p);
}

Eterm
ebif_localtime_to_universaltime_2(Process* p, Eterm arg1, Eterm arg2)
{
    return localtime_to_universaltime_2(p, arg1, arg2);
}

Eterm
ebif_make_ref_0(Process* p)
{
    return make_ref_0(p);
}

Eterm
ebif_md5_1(Process* p, Eterm arg1)
{
    return md5_1(p, arg1);
}

Eterm
ebif_md5_init_0(Process* p)
{
    return md5_init_0(p);
}

Eterm
ebif_md5_update_2(Process* p, Eterm arg1, Eterm arg2)
{
    return md5_update_2(p, arg1, arg2);
}

Eterm
ebif_md5_final_1(Process* p, Eterm arg1)
{
    return md5_final_1(p, arg1);
}

Eterm
ebif_memory_0(Process* p)
{
    return memory_0(p);
}

Eterm
ebif_memory_1(Process* p, Eterm arg1)
{
    return memory_1(p, arg1);
}

Eterm
ebif_is_loaded_1(Process* p, Eterm arg1)
{
    return module_loaded_1(p, arg1);
}

Eterm
ebif_is_loaded_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3)
{
    return function_exported_3(p, arg1, arg2, arg3);
}

Eterm
ebif_monitor_node_2(Process* p, Eterm arg1, Eterm arg2)
{
    return monitor_node_2(p, arg1, arg2);
}

Eterm
ebif_monitor_node_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3)
{
    return monitor_node_3(p, arg1, arg2, arg3);
}

Eterm
ebif_node_1(Process* p, Eterm arg1)
{
    return node_1(p, arg1);
}

Eterm
ebif_node_0(Process* p)
{
    return node_0(p);
}

Eterm
ebif_nodes_1(Process* p, Eterm arg1)
{
    return nodes_1(p, arg1);
}

Eterm
ebif_now_0(Process* p)
{
    return now_0(p);
}

Eterm
ebif_open_port_2(Process* p, Eterm arg1, Eterm arg2)
{
    return open_port_2(p, arg1, arg2);
}

Eterm
ebif_pid_to_string_1(Process* p, Eterm arg1)
{
    return pid_to_list_1(p, arg1);
}

Eterm
ebif_port_info_1(Process* p, Eterm arg1)
{
    return port_info_1(p, arg1);
}

Eterm
ebif_port_info_2(Process* p, Eterm arg1, Eterm arg2)
{
    return port_info_2(p, arg1, arg2);
}

Eterm
ebif_ports_0(Process* p)
{
    return ports_0(p);
}

Eterm
ebif_pre_loaded_0(Process* p)
{
    return pre_loaded_0(p);
}

Eterm
ebif_process_flag_2(Process* p, Eterm arg1, Eterm arg2)
{
    return process_flag_2(p, arg1, arg2);
}

Eterm
ebif_process_flag_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3)
{
    return process_flag_3(p, arg1, arg2, arg3);
}

Eterm
ebif_process_info_1(Process* p, Eterm arg1)
{
    return process_info_1(p, arg1);
}

Eterm
ebif_process_info_2(Process* p, Eterm arg1, Eterm arg2)
{
    return process_info_2(p, arg1, arg2);
}

Eterm
ebif_processes_0(Process* p)
{
    return processes_0(p);
}

Eterm
ebif_purge_module_1(Process* p, Eterm arg1)
{
    return purge_module_1(p, arg1);
}

Eterm
ebif_put_2(Process* p, Eterm arg1, Eterm arg2)
{
    return put_2(p, arg1, arg2);
}

Eterm
ebif_register_2(Process* p, Eterm arg1, Eterm arg2)
{
    return register_2(p, arg1, arg2);
}

Eterm
ebif_registered_0(Process* p)
{
    return registered_0(p);
}

Eterm
ebif_round_1(Process* p, Eterm arg1)
{
    return round_1(p, arg1);
}

Eterm
ebif_self_0(Process* p)
{
    return self_0(p);
}

Eterm
ebif_setelement_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3)
{
    return setelement_3(p, arg1, arg2, arg3);
}

Eterm
ebif_size_1(Process* p, Eterm arg1)
{
    return size_1(p, arg1);
}

Eterm
ebif_spawn_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3)
{
    return spawn_3(p, arg1, arg2, arg3);
}

Eterm
ebif_spawn_link_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3)
{
    return spawn_link_3(p, arg1, arg2, arg3);
}

Eterm
ebif_split_binary_2(Process* p, Eterm arg1, Eterm arg2)
{
    return split_binary_2(p, arg1, arg2);
}

Eterm
ebif_statistics_1(Process* p, Eterm arg1)
{
    return statistics_1(p, arg1);
}

Eterm
ebif_term_to_binary_1(Process* p, Eterm arg1)
{
    return term_to_binary_1(p, arg1);
}

Eterm
ebif_term_to_binary_2(Process* p, Eterm arg1, Eterm arg2)
{
    return term_to_binary_2(p, arg1, arg2);
}

Eterm
ebif_throw_1(Process* p, Eterm arg1)
{
    return throw_1(p, arg1);
}

Eterm
ebif_time_0(Process* p)
{
    return time_0(p);
}

Eterm
ebif_tl_1(Process* p, Eterm arg1)
{
    return tl_1(p, arg1);
}

Eterm
ebif_trunc_1(Process* p, Eterm arg1)
{
    return trunc_1(p, arg1);
}

Eterm
ebif_tuple_to_list_1(Process* p, Eterm arg1)
{
    return tuple_to_list_1(p, arg1);
}

Eterm
ebif_universaltime_0(Process* p)
{
    return universaltime_0(p);
}

Eterm
ebif_universaltime_to_localtime_1(Process* p, Eterm arg1)
{
    return universaltime_to_localtime_1(p, arg1);
}

Eterm
ebif_unlink_1(Process* p, Eterm arg1)
{
    return unlink_1(p, arg1);
}

Eterm
ebif_unregister_1(Process* p, Eterm arg1)
{
    return unregister_1(p, arg1);
}

Eterm
ebif_whereis_1(Process* p, Eterm arg1)
{
    return whereis_1(p, arg1);
}

Eterm
ebif_spawn_opt_1(Process* p, Eterm arg1)
{
    return spawn_opt_1(p, arg1);
}

Eterm
ebif_port_call_2(Process* p, Eterm arg1, Eterm arg2)
{
    return port_call_2(p, arg1, arg2);
}

Eterm
ebif_port_call_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3)
{
    return port_call_3(p, arg1, arg2, arg3);
}

Eterm
ebif_port_command_2(Process* p, Eterm arg1, Eterm arg2)
{
    return port_command_2(p, arg1, arg2);
}

Eterm
ebif_port_command_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3)
{
    return port_command_3(p, arg1, arg2, arg3);
}

Eterm
ebif_port_control_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3)
{
    return port_control_3(p, arg1, arg2, arg3);
}

Eterm
ebif_port_close_1(Process* p, Eterm arg1)
{
    return port_close_1(p, arg1);
}

Eterm
ebif_port_connect_2(Process* p, Eterm arg1, Eterm arg2)
{
    return port_connect_2(p, arg1, arg2);
}

Eterm
ebif_port_set_data_2(Process* p, Eterm arg1, Eterm arg2)
{
    return port_set_data_2(p, arg1, arg2);
}

Eterm
ebif_port_get_data_1(Process* p, Eterm arg1)
{
    return port_get_data_1(p, arg1);
}

Eterm
ebif_trace_pattern_2(Process* p, Eterm arg1, Eterm arg2)
{
    return trace_pattern_2(p, arg1, arg2);
}

Eterm
ebif_trace_pattern_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3)
{
    return trace_pattern_3(p, arg1, arg2, arg3);
}

Eterm
ebif_trace_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3)
{
    return trace_3(p, arg1, arg2, arg3);
}

Eterm
ebif_trace_info_2(Process* p, Eterm arg1, Eterm arg2)
{
    return trace_info_2(p, arg1, arg2);
}

Eterm
ebif_trace_delivered_1(Process* p, Eterm arg1)
{
    return trace_delivered_1(p, arg1);
}

Eterm
ebif_seq_trace_2(Process* p, Eterm arg1, Eterm arg2)
{
    return seq_trace_2(p, arg1, arg2);
}

Eterm
ebif_seq_trace_info_1(Process* p, Eterm arg1)
{
    return seq_trace_info_1(p, arg1);
}

Eterm
ebif_seq_trace_print_1(Process* p, Eterm arg1)
{
    return seq_trace_print_1(p, arg1);
}

Eterm
ebif_seq_trace_print_2(Process* p, Eterm arg1, Eterm arg2)
{
    return seq_trace_print_2(p, arg1, arg2);
}

Eterm
ebif_suspend_process_2(Process* p, Eterm arg1, Eterm arg2)
{
    return suspend_process_2(p, arg1, arg2);
}

Eterm
ebif_resume_process_1(Process* p, Eterm arg1)
{
    return resume_process_1(p, arg1);
}

Eterm
ebif_process_display_2(Process* p, Eterm arg1, Eterm arg2)
{
    return process_display_2(p, arg1, arg2);
}

Eterm
ebif_bump_reductions_1(Process* p, Eterm arg1)
{
    return bump_reductions_1(p, arg1);
}

Eterm
ebif_math_cos_1(Process* p, Eterm arg1)
{
    return math_cos_1(p, arg1);
}

Eterm
ebif_math_cosh_1(Process* p, Eterm arg1)
{
    return math_cosh_1(p, arg1);
}

Eterm
ebif_math_sin_1(Process* p, Eterm arg1)
{
    return math_sin_1(p, arg1);
}

Eterm
ebif_math_sinh_1(Process* p, Eterm arg1)
{
    return math_sinh_1(p, arg1);
}

Eterm
ebif_math_tan_1(Process* p, Eterm arg1)
{
    return math_tan_1(p, arg1);
}

Eterm
ebif_math_tanh_1(Process* p, Eterm arg1)
{
    return math_tanh_1(p, arg1);
}

Eterm
ebif_math_acos_1(Process* p, Eterm arg1)
{
    return math_acos_1(p, arg1);
}

Eterm
ebif_math_acosh_1(Process* p, Eterm arg1)
{
    return math_acosh_1(p, arg1);
}

Eterm
ebif_math_asin_1(Process* p, Eterm arg1)
{
    return math_asin_1(p, arg1);
}

Eterm
ebif_math_asinh_1(Process* p, Eterm arg1)
{
    return math_asinh_1(p, arg1);
}

Eterm
ebif_math_atan_1(Process* p, Eterm arg1)
{
    return math_atan_1(p, arg1);
}

Eterm
ebif_math_atanh_1(Process* p, Eterm arg1)
{
    return math_atanh_1(p, arg1);
}

Eterm
ebif_math_erf_1(Process* p, Eterm arg1)
{
    return math_erf_1(p, arg1);
}

Eterm
ebif_math_erfc_1(Process* p, Eterm arg1)
{
    return math_erfc_1(p, arg1);
}

Eterm
ebif_math_exp_1(Process* p, Eterm arg1)
{
    return math_exp_1(p, arg1);
}

Eterm
ebif_math_log_1(Process* p, Eterm arg1)
{
    return math_log_1(p, arg1);
}

Eterm
ebif_math_log10_1(Process* p, Eterm arg1)
{
    return math_log10_1(p, arg1);
}

Eterm
ebif_math_sqrt_1(Process* p, Eterm arg1)
{
    return math_sqrt_1(p, arg1);
}

Eterm
ebif_math_atan2_2(Process* p, Eterm arg1, Eterm arg2)
{
    return math_atan2_2(p, arg1, arg2);
}

Eterm
ebif_math_pow_2(Process* p, Eterm arg1, Eterm arg2)
{
    return math_pow_2(p, arg1, arg2);
}

Eterm
ebif_start_timer_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3)
{
    return start_timer_3(p, arg1, arg2, arg3);
}

Eterm
ebif_send_after_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3)
{
    return send_after_3(p, arg1, arg2, arg3);
}

Eterm
ebif_cancel_timer_1(Process* p, Eterm arg1)
{
    return cancel_timer_1(p, arg1);
}

Eterm
ebif_read_timer_1(Process* p, Eterm arg1)
{
    return read_timer_1(p, arg1);
}

Eterm
ebif_make_tuple_2(Process* p, Eterm arg1, Eterm arg2)
{
    return make_tuple_2(p, arg1, arg2);
}

Eterm
ebif_append_element_2(Process* p, Eterm arg1, Eterm arg2)
{
    return append_element_2(p, arg1, arg2);
}

Eterm
ebif_system_flag_2(Process* p, Eterm arg1, Eterm arg2)
{
    return system_flag_2(p, arg1, arg2);
}

Eterm
ebif_system_info_1(Process* p, Eterm arg1)
{
    return system_info_1(p, arg1);
}

Eterm
ebif_system_monitor_0(Process* p)
{
    return system_monitor_0(p);
}

Eterm
ebif_system_monitor_1(Process* p, Eterm arg1)
{
    return system_monitor_1(p, arg1);
}

Eterm
ebif_system_monitor_2(Process* p, Eterm arg1, Eterm arg2)
{
    return system_monitor_2(p, arg1, arg2);
}

Eterm
ebif_system_profile_2(Process* p, Eterm arg1, Eterm arg2)
{
    return system_profile_2(p, arg1, arg2);
}

Eterm
ebif_system_profile_0(Process* p)
{
    return system_profile_0(p);
}

Eterm
ebif_ref_to_string_1(Process* p, Eterm arg1)
{
    return ref_to_list_1(p, arg1);
}

Eterm
ebif_port_to_string_1(Process* p, Eterm arg1)
{
    return port_to_list_1(p, arg1);
}

Eterm
ebif_fun_to_string_1(Process* p, Eterm arg1)
{
    return fun_to_list_1(p, arg1);
}

Eterm
ebif_monitor_2(Process* p, Eterm arg1, Eterm arg2)
{
    return monitor_2(p, arg1, arg2);
}

Eterm
ebif_demonitor_1(Process* p, Eterm arg1)
{
    return demonitor_1(p, arg1);
}

Eterm
ebif_demonitor_2(Process* p, Eterm arg1, Eterm arg2)
{
    return demonitor_2(p, arg1, arg2);
}

Eterm
ebif_proc_is_alive_1(Process* p, Eterm arg1)
{
    return is_process_alive_1(p, arg1);
}

Eterm
ebif_error_1(Process* p, Eterm arg1)
{
    return error_1(p, arg1);
}

Eterm
ebif_error_2(Process* p, Eterm arg1, Eterm arg2)
{
    return error_2(p, arg1, arg2);
}

Eterm
ebif_raise_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3)
{
    return raise_3(p, arg1, arg2, arg3);
}

Eterm
ebif_get_stacktrace_0(Process* p)
{
    return get_stacktrace_0(p);
}

Eterm
ebif_is_builtin_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3)
{
    return is_builtin_3(p, arg1, arg2, arg3);
}

Eterm
ebif_and_2(Process* p, Eterm arg1, Eterm arg2)
{
    return and_2(p, arg1, arg2);
}

Eterm
ebif_or_2(Process* p, Eterm arg1, Eterm arg2)
{
    return or_2(p, arg1, arg2);
}

Eterm
ebif_xor_2(Process* p, Eterm arg1, Eterm arg2)
{
    return xor_2(p, arg1, arg2);
}

Eterm
ebif_not_1(Process* p, Eterm arg1)
{
    return not_1(p, arg1);
}

Eterm
ebif_gt_2(Process* p, Eterm arg1, Eterm arg2)
{
    return sgt_2(p, arg1, arg2);
}

Eterm
ebif_ge_2(Process* p, Eterm arg1, Eterm arg2)
{
    return sge_2(p, arg1, arg2);
}

Eterm
ebif_lt_2(Process* p, Eterm arg1, Eterm arg2)
{
    return slt_2(p, arg1, arg2);
}

Eterm
ebif_le_2(Process* p, Eterm arg1, Eterm arg2)
{
    return sle_2(p, arg1, arg2);
}

Eterm
ebif_eq_2(Process* p, Eterm arg1, Eterm arg2)
{
    return seq_2(p, arg1, arg2);
}

Eterm
ebif_areq_2(Process* p, Eterm arg1, Eterm arg2)
{
    return seqeq_2(p, arg1, arg2);
}

Eterm
ebif_neq_2(Process* p, Eterm arg1, Eterm arg2)
{
    return sneq_2(p, arg1, arg2);
}

Eterm
ebif_nareq_2(Process* p, Eterm arg1, Eterm arg2)
{
    return sneqeq_2(p, arg1, arg2);
}

Eterm
ebif_plus_2(Process* p, Eterm arg1, Eterm arg2)
{
    return splus_2(p, arg1, arg2);
}

Eterm
ebif_minus_2(Process* p, Eterm arg1, Eterm arg2)
{
    return sminus_2(p, arg1, arg2);
}

Eterm
ebif_multiply_2(Process* p, Eterm arg1, Eterm arg2)
{
    return stimes_2(p, arg1, arg2);
}

Eterm
ebif_divide_2(Process* p, Eterm arg1, Eterm arg2)
{
    return div_2(p, arg1, arg2);
}

Eterm
ebif_intdiv_2(Process* p, Eterm arg1, Eterm arg2)
{
    return intdiv_2(p, arg1, arg2);
}

Eterm
ebif_rem_2(Process* p, Eterm arg1, Eterm arg2)
{
    return rem_2(p, arg1, arg2);
}

Eterm
ebif_bor_2(Process* p, Eterm arg1, Eterm arg2)
{
    return bor_2(p, arg1, arg2);
}

Eterm
ebif_band_2(Process* p, Eterm arg1, Eterm arg2)
{
    return band_2(p, arg1, arg2);
}

Eterm
ebif_bxor_2(Process* p, Eterm arg1, Eterm arg2)
{
    return bxor_2(p, arg1, arg2);
}

Eterm
ebif_bsl_2(Process* p, Eterm arg1, Eterm arg2)
{
    return bsl_2(p, arg1, arg2);
}

Eterm
ebif_bsr_2(Process* p, Eterm arg1, Eterm arg2)
{
    return bsr_2(p, arg1, arg2);
}

Eterm
ebif_bnot_1(Process* p, Eterm arg1)
{
    return bnot_1(p, arg1);
}

Eterm
ebif_minus_1(Process* p, Eterm arg1)
{
    return sminus_1(p, arg1);
}

Eterm
ebif_plus_1(Process* p, Eterm arg1)
{
    return splus_1(p, arg1);
}

Eterm
ebif_send_2(Process* p, Eterm arg1, Eterm arg2)
{
    return send_2(p, arg1, arg2);
}

Eterm
ebif_send_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3)
{
    return send_3(p, arg1, arg2, arg3);
}

Eterm
ebif_append_2(Process* p, Eterm arg1, Eterm arg2)
{
    return ebif_plusplus_2(p, arg1, arg2);
}

Eterm
ebif_list_subtract_2(Process* p, Eterm arg1, Eterm arg2)
{
    return ebif_minusminus_2(p, arg1, arg2);
}

Eterm
ebif_is_atom_1(Process* p, Eterm arg1)
{
    return is_atom_1(p, arg1);
}

Eterm
ebif_is_list_1(Process* p, Eterm arg1)
{
    return is_list_1(p, arg1);
}

Eterm
ebif_is_tuple_1(Process* p, Eterm arg1)
{
    return is_tuple_1(p, arg1);
}

Eterm
ebif_is_float_1(Process* p, Eterm arg1)
{
    return is_float_1(p, arg1);
}

Eterm
ebif_is_integer_1(Process* p, Eterm arg1)
{
    return is_integer_1(p, arg1);
}

Eterm
ebif_is_number_1(Process* p, Eterm arg1)
{
    return is_number_1(p, arg1);
}

Eterm
ebif_is_pid_1(Process* p, Eterm arg1)
{
    return is_pid_1(p, arg1);
}

Eterm
ebif_is_port_1(Process* p, Eterm arg1)
{
    return is_port_1(p, arg1);
}

Eterm
ebif_is_reference_1(Process* p, Eterm arg1)
{
    return is_reference_1(p, arg1);
}

Eterm
ebif_is_binary_1(Process* p, Eterm arg1)
{
    return is_binary_1(p, arg1);
}

Eterm
ebif_is_function_1(Process* p, Eterm arg1)
{
    return is_function_1(p, arg1);
}

Eterm
ebif_is_function_2(Process* p, Eterm arg1, Eterm arg2)
{
    return is_function_2(p, arg1, arg2);
}

Eterm
ebif_is_record_2(Process* p, Eterm arg1, Eterm arg2)
{
    return is_record_2(p, arg1, arg2);
}

Eterm
ebif_is_record_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3)
{
    return is_record_3(p, arg1, arg2, arg3);
}

Eterm
ebif_ets_all_0(Process* p)
{
    return ets_all_0(p);
}

Eterm
ebif_ets_new_2(Process* p, Eterm arg1, Eterm arg2)
{
    return ets_new_2(p, arg1, arg2);
}

Eterm
ebif_ets_delete_1(Process* p, Eterm arg1)
{
    return ets_delete_1(p, arg1);
}

Eterm
ebif_ets_delete_2(Process* p, Eterm arg1, Eterm arg2)
{
    return ets_delete_2(p, arg1, arg2);
}

Eterm
ebif_ets_delete_all_objects_1(Process* p, Eterm arg1)
{
    return ets_delete_all_objects_1(p, arg1);
}

Eterm
ebif_ets_delete_object_2(Process* p, Eterm arg1, Eterm arg2)
{
    return ets_delete_object_2(p, arg1, arg2);
}

Eterm
ebif_ets_first_1(Process* p, Eterm arg1)
{
    return ets_first_1(p, arg1);
}

Eterm
ebif_ets_is_compiled_ms_1(Process* p, Eterm arg1)
{
    return ets_is_compiled_ms_1(p, arg1);
}

Eterm
ebif_ets_lookup_2(Process* p, Eterm arg1, Eterm arg2)
{
    return ets_lookup_2(p, arg1, arg2);
}

Eterm
ebif_ets_lookup_element_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3)
{
    return ets_lookup_element_3(p, arg1, arg2, arg3);
}

Eterm
ebif_ets_info_1(Process* p, Eterm arg1)
{
    return ets_info_1(p, arg1);
}

Eterm
ebif_ets_info_2(Process* p, Eterm arg1, Eterm arg2)
{
    return ets_info_2(p, arg1, arg2);
}

Eterm
ebif_ets_last_1(Process* p, Eterm arg1)
{
    return ets_last_1(p, arg1);
}

Eterm
ebif_ets_match_1(Process* p, Eterm arg1)
{
    return ets_match_1(p, arg1);
}

Eterm
ebif_ets_match_2(Process* p, Eterm arg1, Eterm arg2)
{
    return ets_match_2(p, arg1, arg2);
}

Eterm
ebif_ets_match_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3)
{
    return ets_match_3(p, arg1, arg2, arg3);
}

Eterm
ebif_ets_match_object_1(Process* p, Eterm arg1)
{
    return ets_match_object_1(p, arg1);
}

Eterm
ebif_ets_match_object_2(Process* p, Eterm arg1, Eterm arg2)
{
    return ets_match_object_2(p, arg1, arg2);
}

Eterm
ebif_ets_match_object_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3)
{
    return ets_match_object_3(p, arg1, arg2, arg3);
}

Eterm
ebif_ets_member_2(Process* p, Eterm arg1, Eterm arg2)
{
    return ets_member_2(p, arg1, arg2);
}

Eterm
ebif_ets_next_2(Process* p, Eterm arg1, Eterm arg2)
{
    return ets_next_2(p, arg1, arg2);
}

Eterm
ebif_ets_prev_2(Process* p, Eterm arg1, Eterm arg2)
{
    return ets_prev_2(p, arg1, arg2);
}

Eterm
ebif_ets_insert_2(Process* p, Eterm arg1, Eterm arg2)
{
    return ets_insert_2(p, arg1, arg2);
}

Eterm
ebif_ets_insert_new_2(Process* p, Eterm arg1, Eterm arg2)
{
    return ets_insert_new_2(p, arg1, arg2);
}

Eterm
ebif_ets_rename_2(Process* p, Eterm arg1, Eterm arg2)
{
    return ets_rename_2(p, arg1, arg2);
}

Eterm
ebif_ets_safe_fixtable_2(Process* p, Eterm arg1, Eterm arg2)
{
    return ets_safe_fixtable_2(p, arg1, arg2);
}

Eterm
ebif_ets_slot_2(Process* p, Eterm arg1, Eterm arg2)
{
    return ets_slot_2(p, arg1, arg2);
}

Eterm
ebif_ets_update_counter_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3)
{
    return ets_update_counter_3(p, arg1, arg2, arg3);
}

Eterm
ebif_ets_select_1(Process* p, Eterm arg1)
{
    return ets_select_1(p, arg1);
}

Eterm
ebif_ets_select_2(Process* p, Eterm arg1, Eterm arg2)
{
    return ets_select_2(p, arg1, arg2);
}

Eterm
ebif_ets_select_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3)
{
    return ets_select_3(p, arg1, arg2, arg3);
}

Eterm
ebif_ets_select_count_2(Process* p, Eterm arg1, Eterm arg2)
{
    return ets_select_count_2(p, arg1, arg2);
}

Eterm
ebif_ets_select_reverse_1(Process* p, Eterm arg1)
{
    return ets_select_reverse_1(p, arg1);
}

Eterm
ebif_ets_select_reverse_2(Process* p, Eterm arg1, Eterm arg2)
{
    return ets_select_reverse_2(p, arg1, arg2);
}

Eterm
ebif_ets_select_reverse_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3)
{
    return ets_select_reverse_3(p, arg1, arg2, arg3);
}

Eterm
ebif_ets_select_delete_2(Process* p, Eterm arg1, Eterm arg2)
{
    return ets_select_delete_2(p, arg1, arg2);
}

Eterm
ebif_ets_match_spec_compile_1(Process* p, Eterm arg1)
{
    return ets_match_spec_compile_1(p, arg1);
}

Eterm
ebif_ets_match_spec_run_r_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3)
{
    return ets_match_spec_run_r_3(p, arg1, arg2, arg3);
}

Eterm
ebif_os_setenv_2(Process* p, Eterm arg1, Eterm arg2)
{
    return os_putenv_2(p, arg1, arg2);
}

Eterm
ebif_os_getenv_0(Process* p)
{
    return os_getenv_0(p);
}

Eterm
ebif_os_getenv_1(Process* p, Eterm arg1)
{
    return os_getenv_1(p, arg1);
}

Eterm
ebif_os_pid_0(Process* p)
{
    return os_getpid_0(p);
}

Eterm
ebif_os_timestamp_0(Process* p)
{
    return os_timestamp_0(p);
}

Eterm
ebif_list_is_element_2(Process* p, Eterm arg1, Eterm arg2)
{
    return lists_member_2(p, arg1, arg2);
}

Eterm
ebif_list_reverse_2(Process* p, Eterm arg1, Eterm arg2)
{
    return lists_reverse_2(p, arg1, arg2);
}

Eterm
ebif_keylist_is_element_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3)
{
    return lists_keymember_3(p, arg1, arg2, arg3);
}

Eterm
ebif_keylist_search_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3)
{
    return lists_keysearch_3(p, arg1, arg2, arg3);
}

Eterm
ebif_erts_debug_disassemble_1(Process* p, Eterm arg1)
{
    return erts_debug_disassemble_1(p, arg1);
}

Eterm
ebif_erts_debug_breakpoint_2(Process* p, Eterm arg1, Eterm arg2)
{
    return erts_debug_breakpoint_2(p, arg1, arg2);
}

Eterm
ebif_erts_debug_same_2(Process* p, Eterm arg1, Eterm arg2)
{
    return erts_debug_same_2(p, arg1, arg2);
}

Eterm
ebif_erts_debug_flat_size_1(Process* p, Eterm arg1)
{
    return erts_debug_flat_size_1(p, arg1);
}

Eterm
ebif_erts_debug_get_internal_state_1(Process* p, Eterm arg1)
{
    return erts_debug_get_internal_state_1(p, arg1);
}

Eterm
ebif_erts_debug_set_internal_state_2(Process* p, Eterm arg1, Eterm arg2)
{
    return erts_debug_set_internal_state_2(p, arg1, arg2);
}

Eterm
ebif_erts_debug_display_1(Process* p, Eterm arg1)
{
    return erts_debug_display_1(p, arg1);
}

Eterm
ebif_erts_debug_dist_ext_to_term_2(Process* p, Eterm arg1, Eterm arg2)
{
    return erts_debug_dist_ext_to_term_2(p, arg1, arg2);
}

Eterm
ebif_code_get_chunk_2(Process* p, Eterm arg1, Eterm arg2)
{
    return code_get_chunk_2(p, arg1, arg2);
}

Eterm
ebif_code_module_md5_1(Process* p, Eterm arg1)
{
    return code_module_md5_1(p, arg1);
}

Eterm
ebif_code_make_stub_module_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3)
{
    return code_make_stub_module_3(p, arg1, arg2, arg3);
}

Eterm
ebif_code_is_native_1(Process* p, Eterm arg1)
{
    return code_is_module_native_1(p, arg1);
}

