/*
 *  Warning: Do not edit this file.  It was automatically
 *  generated by 'make_tables' on Mon Sep 13 15:06:40 2010.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif /* HAVE_CONFIG_H */
#include "export.h"
#include "sys.h"
#include "erl_vm.h"
#include "global.h"
#include "erl_process.h"
#include "bif.h"
#include "erl_bif_table.h"
#include "erl_atom_table.h"

Eterm
wrap_adler32_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(2, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_adler32_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(3, p, arg1, 0, 0, I);
}

Eterm
wrap_adler32_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(4, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_adler32_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(5, p, arg1, arg2, 0, I);
}

Eterm
wrap_adler32_combine_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(6, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ebif_adler32_combine_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(7, p, arg1, arg2, arg3, I);
}

Eterm
wrap_apply_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(8, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ebif_apply_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(9, p, arg1, arg2, arg3, I);
}

Eterm
wrap_atom_to_list_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(10, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_atom_to_string_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(11, p, arg1, 0, 0, I);
}

Eterm
wrap_binary_to_list_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(12, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_binary_to_list_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(13, p, arg1, 0, 0, I);
}

Eterm
wrap_binary_to_list_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(14, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ebif_binary_to_list_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(15, p, arg1, arg2, arg3, I);
}

Eterm
wrap_binary_to_term_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(16, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_binary_to_term_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(17, p, arg1, 0, 0, I);
}

Eterm
wrap_check_process_code_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(18, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_check_process_code_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(19, p, arg1, arg2, 0, I);
}

Eterm
wrap_crc32_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(20, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_crc32_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(21, p, arg1, 0, 0, I);
}

Eterm
wrap_crc32_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(22, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_crc32_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(23, p, arg1, arg2, 0, I);
}

Eterm
wrap_crc32_combine_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(24, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ebif_crc32_combine_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(25, p, arg1, arg2, arg3, I);
}

Eterm
wrap_date_0(Process* p, UWord *I)
{
    return erts_bif_trace(26, p, 0, 0, 0, I);
}

Eterm
wrap_ebif_date_0(Process* p, UWord *I)
{
    return erts_bif_trace(27, p, 0, 0, 0, I);
}

Eterm
wrap_delete_module_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(28, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_delete_module_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(29, p, arg1, 0, 0, I);
}

Eterm
wrap_display_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(30, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_display_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(31, p, arg1, 0, 0, I);
}

Eterm
wrap_display_string_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(32, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_display_string_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(33, p, arg1, 0, 0, I);
}

Eterm
wrap_display_nl_0(Process* p, UWord *I)
{
    return erts_bif_trace(34, p, 0, 0, 0, I);
}

Eterm
wrap_ebif_display_nl_0(Process* p, UWord *I)
{
    return erts_bif_trace(35, p, 0, 0, 0, I);
}

Eterm
wrap_erase_0(Process* p, UWord *I)
{
    return erts_bif_trace(38, p, 0, 0, 0, I);
}

Eterm
wrap_ebif_erase_0(Process* p, UWord *I)
{
    return erts_bif_trace(39, p, 0, 0, 0, I);
}

Eterm
wrap_erase_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(40, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_erase_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(41, p, arg1, 0, 0, I);
}

Eterm
wrap_exit_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(42, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_exit_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(43, p, arg1, 0, 0, I);
}

Eterm
wrap_exit_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(44, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_signal_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(45, p, arg1, arg2, 0, I);
}

Eterm
wrap_external_size_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(46, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_external_size_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(47, p, arg1, 0, 0, I);
}

Eterm
wrap_float_to_list_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(50, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_float_to_string_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(51, p, arg1, 0, 0, I);
}

Eterm
wrap_fun_info_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(52, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_fun_info_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(53, p, arg1, arg2, 0, I);
}

Eterm
wrap_garbage_collect_0(Process* p, UWord *I)
{
    return erts_bif_trace(54, p, 0, 0, 0, I);
}

Eterm
wrap_ebif_garbage_collect_0(Process* p, UWord *I)
{
    return erts_bif_trace(55, p, 0, 0, 0, I);
}

Eterm
wrap_garbage_collect_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(56, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_garbage_collect_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(57, p, arg1, 0, 0, I);
}

Eterm
wrap_garbage_collect_message_area_0(Process* p, UWord *I)
{
    return erts_bif_trace(58, p, 0, 0, 0, I);
}

Eterm
wrap_ebif_garbage_collect_message_area_0(Process* p, UWord *I)
{
    return erts_bif_trace(59, p, 0, 0, 0, I);
}

Eterm
wrap_get_0(Process* p, UWord *I)
{
    return erts_bif_trace(60, p, 0, 0, 0, I);
}

Eterm
wrap_ebif_get_0(Process* p, UWord *I)
{
    return erts_bif_trace(61, p, 0, 0, 0, I);
}

Eterm
wrap_get_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(62, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_get_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(63, p, arg1, 0, 0, I);
}

Eterm
wrap_get_keys_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(64, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_get_keys_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(65, p, arg1, 0, 0, I);
}

Eterm
wrap_group_leader_0(Process* p, UWord *I)
{
    return erts_bif_trace(66, p, 0, 0, 0, I);
}

Eterm
wrap_ebif_group_leader_0(Process* p, UWord *I)
{
    return erts_bif_trace(67, p, 0, 0, 0, I);
}

Eterm
wrap_group_leader_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(68, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_group_leader_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(69, p, arg1, arg2, 0, I);
}

Eterm
wrap_halt_0(Process* p, UWord *I)
{
    return erts_bif_trace(70, p, 0, 0, 0, I);
}

Eterm
wrap_ebif_halt_0(Process* p, UWord *I)
{
    return erts_bif_trace(71, p, 0, 0, 0, I);
}

Eterm
wrap_halt_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(72, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_halt_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(73, p, arg1, 0, 0, I);
}

Eterm
wrap_phash_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(74, p, arg1, arg2, 0, I);
}

Eterm
wrap_phash2_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(75, p, arg1, 0, 0, I);
}

Eterm
wrap_phash2_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(76, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_phash2_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(77, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_phash2_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(78, p, arg1, arg2, 0, I);
}

Eterm
wrap_integer_to_list_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(81, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_integer_to_string_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(82, p, arg1, 0, 0, I);
}

Eterm
wrap_is_alive_0(Process* p, UWord *I)
{
    return erts_bif_trace(83, p, 0, 0, 0, I);
}

Eterm
wrap_ebif_is_alive_0(Process* p, UWord *I)
{
    return erts_bif_trace(84, p, 0, 0, 0, I);
}

Eterm
wrap_link_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(87, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_link_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(88, p, arg1, 0, 0, I);
}

Eterm
wrap_list_to_atom_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(89, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_string_to_atom_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(90, p, arg1, 0, 0, I);
}

Eterm
wrap_list_to_binary_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(91, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_list_to_binary_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(92, p, arg1, 0, 0, I);
}

Eterm
wrap_list_to_float_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(93, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_string_to_float_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(94, p, arg1, 0, 0, I);
}

Eterm
wrap_list_to_integer_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(95, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_string_to_integer_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(96, p, arg1, 0, 0, I);
}

Eterm
wrap_list_to_pid_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(97, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_string_to_pid_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(98, p, arg1, 0, 0, I);
}

Eterm
wrap_list_to_tuple_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(99, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_list_to_tuple_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(100, p, arg1, 0, 0, I);
}

Eterm
wrap_load_module_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(101, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_load_module_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(102, p, arg1, arg2, 0, I);
}

Eterm
wrap_loaded_0(Process* p, UWord *I)
{
    return erts_bif_trace(103, p, 0, 0, 0, I);
}

Eterm
wrap_ebif_loaded_0(Process* p, UWord *I)
{
    return erts_bif_trace(104, p, 0, 0, 0, I);
}

Eterm
wrap_localtime_0(Process* p, UWord *I)
{
    return erts_bif_trace(105, p, 0, 0, 0, I);
}

Eterm
wrap_ebif_localtime_0(Process* p, UWord *I)
{
    return erts_bif_trace(106, p, 0, 0, 0, I);
}

Eterm
wrap_localtime_to_universaltime_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(107, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_localtime_to_universaltime_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(108, p, arg1, arg2, 0, I);
}

Eterm
wrap_make_ref_0(Process* p, UWord *I)
{
    return erts_bif_trace(109, p, 0, 0, 0, I);
}

Eterm
wrap_ebif_make_ref_0(Process* p, UWord *I)
{
    return erts_bif_trace(110, p, 0, 0, 0, I);
}

Eterm
wrap_md5_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(111, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_md5_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(112, p, arg1, 0, 0, I);
}

Eterm
wrap_md5_init_0(Process* p, UWord *I)
{
    return erts_bif_trace(113, p, 0, 0, 0, I);
}

Eterm
wrap_ebif_md5_init_0(Process* p, UWord *I)
{
    return erts_bif_trace(114, p, 0, 0, 0, I);
}

Eterm
wrap_md5_update_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(115, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_md5_update_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(116, p, arg1, arg2, 0, I);
}

Eterm
wrap_md5_final_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(117, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_md5_final_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(118, p, arg1, 0, 0, I);
}

Eterm
wrap_memory_0(Process* p, UWord *I)
{
    return erts_bif_trace(119, p, 0, 0, 0, I);
}

Eterm
wrap_ebif_memory_0(Process* p, UWord *I)
{
    return erts_bif_trace(120, p, 0, 0, 0, I);
}

Eterm
wrap_memory_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(121, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_memory_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(122, p, arg1, 0, 0, I);
}

Eterm
wrap_module_loaded_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(123, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_is_loaded_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(124, p, arg1, 0, 0, I);
}

Eterm
wrap_function_exported_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(125, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ebif_is_loaded_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(126, p, arg1, arg2, arg3, I);
}

Eterm
wrap_monitor_node_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(127, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_monitor_node_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(128, p, arg1, arg2, 0, I);
}

Eterm
wrap_monitor_node_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(129, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ebif_monitor_node_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(130, p, arg1, arg2, arg3, I);
}

Eterm
wrap_nodes_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(135, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_nodes_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(136, p, arg1, 0, 0, I);
}

Eterm
wrap_now_0(Process* p, UWord *I)
{
    return erts_bif_trace(137, p, 0, 0, 0, I);
}

Eterm
wrap_ebif_now_0(Process* p, UWord *I)
{
    return erts_bif_trace(138, p, 0, 0, 0, I);
}

Eterm
wrap_open_port_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(139, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_open_port_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(140, p, arg1, arg2, 0, I);
}

Eterm
wrap_pid_to_list_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(141, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_pid_to_string_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(142, p, arg1, 0, 0, I);
}

Eterm
wrap_port_info_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(143, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_port_info_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(144, p, arg1, 0, 0, I);
}

Eterm
wrap_port_info_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(145, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_port_info_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(146, p, arg1, arg2, 0, I);
}

Eterm
wrap_ports_0(Process* p, UWord *I)
{
    return erts_bif_trace(147, p, 0, 0, 0, I);
}

Eterm
wrap_ebif_ports_0(Process* p, UWord *I)
{
    return erts_bif_trace(148, p, 0, 0, 0, I);
}

Eterm
wrap_pre_loaded_0(Process* p, UWord *I)
{
    return erts_bif_trace(149, p, 0, 0, 0, I);
}

Eterm
wrap_ebif_pre_loaded_0(Process* p, UWord *I)
{
    return erts_bif_trace(150, p, 0, 0, 0, I);
}

Eterm
wrap_process_flag_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(151, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_process_flag_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(152, p, arg1, arg2, 0, I);
}

Eterm
wrap_process_flag_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(153, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ebif_process_flag_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(154, p, arg1, arg2, arg3, I);
}

Eterm
wrap_process_info_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(155, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_process_info_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(156, p, arg1, 0, 0, I);
}

Eterm
wrap_process_info_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(157, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_process_info_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(158, p, arg1, arg2, 0, I);
}

Eterm
wrap_processes_0(Process* p, UWord *I)
{
    return erts_bif_trace(159, p, 0, 0, 0, I);
}

Eterm
wrap_ebif_processes_0(Process* p, UWord *I)
{
    return erts_bif_trace(160, p, 0, 0, 0, I);
}

Eterm
wrap_purge_module_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(161, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_purge_module_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(162, p, arg1, 0, 0, I);
}

Eterm
wrap_put_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(163, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_put_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(164, p, arg1, arg2, 0, I);
}

Eterm
wrap_register_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(165, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_register_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(166, p, arg1, arg2, 0, I);
}

Eterm
wrap_registered_0(Process* p, UWord *I)
{
    return erts_bif_trace(167, p, 0, 0, 0, I);
}

Eterm
wrap_ebif_registered_0(Process* p, UWord *I)
{
    return erts_bif_trace(168, p, 0, 0, 0, I);
}

Eterm
wrap_setelement_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(173, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ebif_setelement_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(174, p, arg1, arg2, arg3, I);
}

Eterm
wrap_spawn_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(177, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ebif_spawn_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(178, p, arg1, arg2, arg3, I);
}

Eterm
wrap_spawn_link_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(179, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ebif_spawn_link_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(180, p, arg1, arg2, arg3, I);
}

Eterm
wrap_split_binary_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(181, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_split_binary_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(182, p, arg1, arg2, 0, I);
}

Eterm
wrap_statistics_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(183, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_statistics_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(184, p, arg1, 0, 0, I);
}

Eterm
wrap_term_to_binary_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(185, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_term_to_binary_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(186, p, arg1, 0, 0, I);
}

Eterm
wrap_term_to_binary_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(187, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_term_to_binary_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(188, p, arg1, arg2, 0, I);
}

Eterm
wrap_throw_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(189, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_throw_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(190, p, arg1, 0, 0, I);
}

Eterm
wrap_time_0(Process* p, UWord *I)
{
    return erts_bif_trace(191, p, 0, 0, 0, I);
}

Eterm
wrap_ebif_time_0(Process* p, UWord *I)
{
    return erts_bif_trace(192, p, 0, 0, 0, I);
}

Eterm
wrap_tuple_to_list_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(197, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_tuple_to_list_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(198, p, arg1, 0, 0, I);
}

Eterm
wrap_universaltime_0(Process* p, UWord *I)
{
    return erts_bif_trace(199, p, 0, 0, 0, I);
}

Eterm
wrap_ebif_universaltime_0(Process* p, UWord *I)
{
    return erts_bif_trace(200, p, 0, 0, 0, I);
}

Eterm
wrap_universaltime_to_localtime_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(201, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_universaltime_to_localtime_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(202, p, arg1, 0, 0, I);
}

Eterm
wrap_unlink_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(203, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_unlink_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(204, p, arg1, 0, 0, I);
}

Eterm
wrap_unregister_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(205, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_unregister_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(206, p, arg1, 0, 0, I);
}

Eterm
wrap_whereis_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(207, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_whereis_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(208, p, arg1, 0, 0, I);
}

Eterm
wrap_spawn_opt_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(209, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_spawn_opt_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(210, p, arg1, 0, 0, I);
}

Eterm
wrap_setnode_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(211, p, arg1, arg2, 0, I);
}

Eterm
wrap_setnode_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(212, p, arg1, arg2, arg3, I);
}

Eterm
wrap_dist_exit_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(213, p, arg1, arg2, arg3, I);
}

Eterm
wrap_port_call_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(214, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_port_call_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(215, p, arg1, arg2, 0, I);
}

Eterm
wrap_port_call_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(216, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ebif_port_call_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(217, p, arg1, arg2, arg3, I);
}

Eterm
wrap_port_command_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(218, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_port_command_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(219, p, arg1, arg2, 0, I);
}

Eterm
wrap_port_command_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(220, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ebif_port_command_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(221, p, arg1, arg2, arg3, I);
}

Eterm
wrap_port_control_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(222, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ebif_port_control_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(223, p, arg1, arg2, arg3, I);
}

Eterm
wrap_port_close_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(224, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_port_close_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(225, p, arg1, 0, 0, I);
}

Eterm
wrap_port_connect_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(226, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_port_connect_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(227, p, arg1, arg2, 0, I);
}

Eterm
wrap_port_set_data_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(228, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_port_set_data_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(229, p, arg1, arg2, 0, I);
}

Eterm
wrap_port_get_data_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(230, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_port_get_data_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(231, p, arg1, 0, 0, I);
}

Eterm
wrap_trace_pattern_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(232, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_trace_pattern_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(233, p, arg1, arg2, 0, I);
}

Eterm
wrap_trace_pattern_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(234, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ebif_trace_pattern_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(235, p, arg1, arg2, arg3, I);
}

Eterm
wrap_trace_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(236, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ebif_trace_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(237, p, arg1, arg2, arg3, I);
}

Eterm
wrap_trace_info_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(238, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_trace_info_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(239, p, arg1, arg2, 0, I);
}

Eterm
wrap_trace_delivered_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(240, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_trace_delivered_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(241, p, arg1, 0, 0, I);
}

Eterm
wrap_seq_trace_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(242, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_seq_trace_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(243, p, arg1, arg2, 0, I);
}

Eterm
wrap_seq_trace_info_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(244, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_seq_trace_info_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(245, p, arg1, 0, 0, I);
}

Eterm
wrap_seq_trace_print_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(246, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_seq_trace_print_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(247, p, arg1, 0, 0, I);
}

Eterm
wrap_seq_trace_print_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(248, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_seq_trace_print_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(249, p, arg1, arg2, 0, I);
}

Eterm
wrap_suspend_process_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(250, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_suspend_process_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(251, p, arg1, arg2, 0, I);
}

Eterm
wrap_resume_process_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(252, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_resume_process_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(253, p, arg1, 0, 0, I);
}

Eterm
wrap_process_display_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(254, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_process_display_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(255, p, arg1, arg2, 0, I);
}

Eterm
wrap_bump_reductions_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(256, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_bump_reductions_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(257, p, arg1, 0, 0, I);
}

Eterm
wrap_math_cos_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(258, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_math_cos_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(259, p, arg1, 0, 0, I);
}

Eterm
wrap_math_cosh_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(260, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_math_cosh_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(261, p, arg1, 0, 0, I);
}

Eterm
wrap_math_sin_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(262, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_math_sin_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(263, p, arg1, 0, 0, I);
}

Eterm
wrap_math_sinh_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(264, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_math_sinh_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(265, p, arg1, 0, 0, I);
}

Eterm
wrap_math_tan_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(266, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_math_tan_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(267, p, arg1, 0, 0, I);
}

Eterm
wrap_math_tanh_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(268, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_math_tanh_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(269, p, arg1, 0, 0, I);
}

Eterm
wrap_math_acos_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(270, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_math_acos_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(271, p, arg1, 0, 0, I);
}

Eterm
wrap_math_acosh_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(272, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_math_acosh_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(273, p, arg1, 0, 0, I);
}

Eterm
wrap_math_asin_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(274, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_math_asin_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(275, p, arg1, 0, 0, I);
}

Eterm
wrap_math_asinh_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(276, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_math_asinh_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(277, p, arg1, 0, 0, I);
}

Eterm
wrap_math_atan_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(278, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_math_atan_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(279, p, arg1, 0, 0, I);
}

Eterm
wrap_math_atanh_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(280, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_math_atanh_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(281, p, arg1, 0, 0, I);
}

Eterm
wrap_math_erf_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(282, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_math_erf_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(283, p, arg1, 0, 0, I);
}

Eterm
wrap_math_erfc_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(284, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_math_erfc_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(285, p, arg1, 0, 0, I);
}

Eterm
wrap_math_exp_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(286, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_math_exp_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(287, p, arg1, 0, 0, I);
}

Eterm
wrap_math_log_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(288, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_math_log_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(289, p, arg1, 0, 0, I);
}

Eterm
wrap_math_log10_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(290, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_math_log10_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(291, p, arg1, 0, 0, I);
}

Eterm
wrap_math_sqrt_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(292, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_math_sqrt_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(293, p, arg1, 0, 0, I);
}

Eterm
wrap_math_atan2_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(294, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_math_atan2_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(295, p, arg1, arg2, 0, I);
}

Eterm
wrap_math_pow_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(296, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_math_pow_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(297, p, arg1, arg2, 0, I);
}

Eterm
wrap_start_timer_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(298, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ebif_start_timer_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(299, p, arg1, arg2, arg3, I);
}

Eterm
wrap_send_after_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(300, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ebif_send_after_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(301, p, arg1, arg2, arg3, I);
}

Eterm
wrap_cancel_timer_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(302, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_cancel_timer_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(303, p, arg1, 0, 0, I);
}

Eterm
wrap_read_timer_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(304, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_read_timer_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(305, p, arg1, 0, 0, I);
}

Eterm
wrap_make_tuple_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(306, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_make_tuple_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(307, p, arg1, arg2, 0, I);
}

Eterm
wrap_append_element_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(308, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_append_element_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(309, p, arg1, arg2, 0, I);
}

Eterm
wrap_make_tuple_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(310, p, arg1, arg2, arg3, I);
}

Eterm
wrap_system_flag_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(311, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_system_flag_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(312, p, arg1, arg2, 0, I);
}

Eterm
wrap_system_info_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(313, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_system_info_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(314, p, arg1, 0, 0, I);
}

Eterm
wrap_system_monitor_0(Process* p, UWord *I)
{
    return erts_bif_trace(315, p, 0, 0, 0, I);
}

Eterm
wrap_ebif_system_monitor_0(Process* p, UWord *I)
{
    return erts_bif_trace(316, p, 0, 0, 0, I);
}

Eterm
wrap_system_monitor_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(317, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_system_monitor_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(318, p, arg1, 0, 0, I);
}

Eterm
wrap_system_monitor_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(319, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_system_monitor_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(320, p, arg1, arg2, 0, I);
}

Eterm
wrap_system_profile_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(321, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_system_profile_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(322, p, arg1, arg2, 0, I);
}

Eterm
wrap_system_profile_0(Process* p, UWord *I)
{
    return erts_bif_trace(323, p, 0, 0, 0, I);
}

Eterm
wrap_ebif_system_profile_0(Process* p, UWord *I)
{
    return erts_bif_trace(324, p, 0, 0, 0, I);
}

Eterm
wrap_ref_to_list_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(325, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_ref_to_string_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(326, p, arg1, 0, 0, I);
}

Eterm
wrap_port_to_list_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(327, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_port_to_string_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(328, p, arg1, 0, 0, I);
}

Eterm
wrap_fun_to_list_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(329, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_fun_to_string_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(330, p, arg1, 0, 0, I);
}

Eterm
wrap_monitor_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(331, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_monitor_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(332, p, arg1, arg2, 0, I);
}

Eterm
wrap_demonitor_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(333, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_demonitor_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(334, p, arg1, 0, 0, I);
}

Eterm
wrap_demonitor_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(335, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_demonitor_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(336, p, arg1, arg2, 0, I);
}

Eterm
wrap_is_process_alive_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(337, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_proc_is_alive_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(338, p, arg1, 0, 0, I);
}

Eterm
wrap_error_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(339, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_error_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(340, p, arg1, 0, 0, I);
}

Eterm
wrap_error_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(341, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_error_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(342, p, arg1, arg2, 0, I);
}

Eterm
wrap_raise_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(343, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ebif_raise_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(344, p, arg1, arg2, arg3, I);
}

Eterm
wrap_get_stacktrace_0(Process* p, UWord *I)
{
    return erts_bif_trace(345, p, 0, 0, 0, I);
}

Eterm
wrap_ebif_get_stacktrace_0(Process* p, UWord *I)
{
    return erts_bif_trace(346, p, 0, 0, 0, I);
}

Eterm
wrap_is_builtin_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(347, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ebif_is_builtin_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(348, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ebif_bang_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(401, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_send_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(402, p, arg1, arg2, 0, I);
}

Eterm
wrap_send_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(403, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_send_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(404, p, arg1, arg2, arg3, I);
}

Eterm
wrap_send_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(405, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ebif_plusplus_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(406, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_append_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(407, p, arg1, arg2, 0, I);
}

Eterm
wrap_append_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(408, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_minusminus_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(409, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_list_subtract_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(410, p, arg1, arg2, 0, I);
}

Eterm
wrap_subtract_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(411, p, arg1, arg2, 0, I);
}

Eterm
wrap_match_spec_test_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(440, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ets_all_0(Process* p, UWord *I)
{
    return erts_bif_trace(441, p, 0, 0, 0, I);
}

Eterm
wrap_ebif_ets_all_0(Process* p, UWord *I)
{
    return erts_bif_trace(442, p, 0, 0, 0, I);
}

Eterm
wrap_ets_new_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(443, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_ets_new_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(444, p, arg1, arg2, 0, I);
}

Eterm
wrap_ets_delete_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(445, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_ets_delete_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(446, p, arg1, 0, 0, I);
}

Eterm
wrap_ets_delete_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(447, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_ets_delete_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(448, p, arg1, arg2, 0, I);
}

Eterm
wrap_ets_delete_all_objects_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(449, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_ets_delete_all_objects_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(450, p, arg1, 0, 0, I);
}

Eterm
wrap_ets_delete_object_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(451, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_ets_delete_object_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(452, p, arg1, arg2, 0, I);
}

Eterm
wrap_ets_first_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(453, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_ets_first_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(454, p, arg1, 0, 0, I);
}

Eterm
wrap_ets_is_compiled_ms_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(455, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_ets_is_compiled_ms_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(456, p, arg1, 0, 0, I);
}

Eterm
wrap_ets_lookup_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(457, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_ets_lookup_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(458, p, arg1, arg2, 0, I);
}

Eterm
wrap_ets_lookup_element_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(459, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ebif_ets_lookup_element_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(460, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ets_info_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(461, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_ets_info_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(462, p, arg1, 0, 0, I);
}

Eterm
wrap_ets_info_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(463, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_ets_info_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(464, p, arg1, arg2, 0, I);
}

Eterm
wrap_ets_last_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(465, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_ets_last_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(466, p, arg1, 0, 0, I);
}

Eterm
wrap_ets_match_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(467, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_ets_match_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(468, p, arg1, 0, 0, I);
}

Eterm
wrap_ets_match_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(469, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_ets_match_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(470, p, arg1, arg2, 0, I);
}

Eterm
wrap_ets_match_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(471, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ebif_ets_match_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(472, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ets_match_object_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(473, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_ets_match_object_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(474, p, arg1, 0, 0, I);
}

Eterm
wrap_ets_match_object_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(475, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_ets_match_object_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(476, p, arg1, arg2, 0, I);
}

Eterm
wrap_ets_match_object_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(477, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ebif_ets_match_object_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(478, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ets_member_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(479, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_ets_member_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(480, p, arg1, arg2, 0, I);
}

Eterm
wrap_ets_next_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(481, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_ets_next_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(482, p, arg1, arg2, 0, I);
}

Eterm
wrap_ets_prev_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(483, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_ets_prev_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(484, p, arg1, arg2, 0, I);
}

Eterm
wrap_ets_insert_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(485, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_ets_insert_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(486, p, arg1, arg2, 0, I);
}

Eterm
wrap_ets_insert_new_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(487, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_ets_insert_new_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(488, p, arg1, arg2, 0, I);
}

Eterm
wrap_ets_rename_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(489, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_ets_rename_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(490, p, arg1, arg2, 0, I);
}

Eterm
wrap_ets_safe_fixtable_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(491, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_ets_safe_fixtable_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(492, p, arg1, arg2, 0, I);
}

Eterm
wrap_ets_slot_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(493, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_ets_slot_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(494, p, arg1, arg2, 0, I);
}

Eterm
wrap_ets_update_counter_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(495, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ebif_ets_update_counter_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(496, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ets_select_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(497, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_ets_select_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(498, p, arg1, 0, 0, I);
}

Eterm
wrap_ets_select_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(499, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_ets_select_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(500, p, arg1, arg2, 0, I);
}

Eterm
wrap_ets_select_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(501, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ebif_ets_select_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(502, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ets_select_count_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(503, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_ets_select_count_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(504, p, arg1, arg2, 0, I);
}

Eterm
wrap_ets_select_reverse_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(505, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_ets_select_reverse_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(506, p, arg1, 0, 0, I);
}

Eterm
wrap_ets_select_reverse_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(507, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_ets_select_reverse_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(508, p, arg1, arg2, 0, I);
}

Eterm
wrap_ets_select_reverse_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(509, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ebif_ets_select_reverse_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(510, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ets_select_delete_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(511, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_ets_select_delete_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(512, p, arg1, arg2, 0, I);
}

Eterm
wrap_ets_match_spec_compile_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(513, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_ets_match_spec_compile_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(514, p, arg1, 0, 0, I);
}

Eterm
wrap_ets_match_spec_run_r_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(515, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ebif_ets_match_spec_run_r_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(516, p, arg1, arg2, arg3, I);
}

Eterm
wrap_os_putenv_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(517, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_os_setenv_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(518, p, arg1, arg2, 0, I);
}

Eterm
wrap_os_getenv_0(Process* p, UWord *I)
{
    return erts_bif_trace(519, p, 0, 0, 0, I);
}

Eterm
wrap_ebif_os_getenv_0(Process* p, UWord *I)
{
    return erts_bif_trace(520, p, 0, 0, 0, I);
}

Eterm
wrap_os_getenv_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(521, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_os_getenv_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(522, p, arg1, 0, 0, I);
}

Eterm
wrap_os_getpid_0(Process* p, UWord *I)
{
    return erts_bif_trace(523, p, 0, 0, 0, I);
}

Eterm
wrap_ebif_os_pid_0(Process* p, UWord *I)
{
    return erts_bif_trace(524, p, 0, 0, 0, I);
}

Eterm
wrap_os_timestamp_0(Process* p, UWord *I)
{
    return erts_bif_trace(525, p, 0, 0, 0, I);
}

Eterm
wrap_ebif_os_timestamp_0(Process* p, UWord *I)
{
    return erts_bif_trace(526, p, 0, 0, 0, I);
}

Eterm
wrap_erl_ddll_try_load_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(527, p, arg1, arg2, arg3, I);
}

Eterm
wrap_erl_ddll_try_unload_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(528, p, arg1, arg2, 0, I);
}

Eterm
wrap_erl_ddll_loaded_drivers_0(Process* p, UWord *I)
{
    return erts_bif_trace(529, p, 0, 0, 0, I);
}

Eterm
wrap_erl_ddll_info_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(530, p, arg1, arg2, 0, I);
}

Eterm
wrap_erl_ddll_format_error_int_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(531, p, arg1, 0, 0, I);
}

Eterm
wrap_erl_ddll_monitor_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(532, p, arg1, arg2, 0, I);
}

Eterm
wrap_erl_ddll_demonitor_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(533, p, arg1, 0, 0, I);
}

Eterm
wrap_re_compile_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(534, p, arg1, 0, 0, I);
}

Eterm
wrap_re_compile_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(535, p, arg1, arg2, 0, I);
}

Eterm
wrap_re_run_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(536, p, arg1, arg2, 0, I);
}

Eterm
wrap_re_run_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(537, p, arg1, arg2, arg3, I);
}

Eterm
wrap_lists_member_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(538, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_list_is_element_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(539, p, arg1, arg2, 0, I);
}

Eterm
wrap_lists_reverse_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(540, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_list_reverse_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(541, p, arg1, arg2, 0, I);
}

Eterm
wrap_lists_keymember_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(542, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ebif_keylist_is_element_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(543, p, arg1, arg2, arg3, I);
}

Eterm
wrap_lists_keysearch_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(544, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ebif_keylist_search_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(545, p, arg1, arg2, arg3, I);
}

Eterm
wrap_lists_keyfind_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(546, p, arg1, arg2, arg3, I);
}

Eterm
wrap_erts_debug_disassemble_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(547, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_erts_debug_disassemble_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(548, p, arg1, 0, 0, I);
}

Eterm
wrap_erts_debug_breakpoint_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(549, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_erts_debug_breakpoint_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(550, p, arg1, arg2, 0, I);
}

Eterm
wrap_erts_debug_same_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(551, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_erts_debug_same_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(552, p, arg1, arg2, 0, I);
}

Eterm
wrap_erts_debug_flat_size_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(553, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_erts_debug_flat_size_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(554, p, arg1, 0, 0, I);
}

Eterm
wrap_erts_debug_get_internal_state_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(555, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_erts_debug_get_internal_state_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(556, p, arg1, 0, 0, I);
}

Eterm
wrap_erts_debug_set_internal_state_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(557, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_erts_debug_set_internal_state_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(558, p, arg1, arg2, 0, I);
}

Eterm
wrap_erts_debug_display_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(559, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_erts_debug_display_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(560, p, arg1, 0, 0, I);
}

Eterm
wrap_erts_debug_dist_ext_to_term_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(561, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_erts_debug_dist_ext_to_term_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(562, p, arg1, arg2, 0, I);
}

Eterm
wrap_erts_debug_dump_monitors_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(563, p, arg1, 0, 0, I);
}

Eterm
wrap_erts_debug_dump_links_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(564, p, arg1, 0, 0, I);
}

Eterm
wrap_erts_debug_lock_counters_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(565, p, arg1, 0, 0, I);
}

Eterm
wrap_code_get_chunk_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(566, p, arg1, arg2, 0, I);
}

Eterm
wrap_ebif_code_get_chunk_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(567, p, arg1, arg2, 0, I);
}

Eterm
wrap_code_module_md5_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(568, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_code_module_md5_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(569, p, arg1, 0, 0, I);
}

Eterm
wrap_code_make_stub_module_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(570, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ebif_code_make_stub_module_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(571, p, arg1, arg2, arg3, I);
}

Eterm
wrap_code_is_module_native_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(572, p, arg1, 0, 0, I);
}

Eterm
wrap_ebif_code_is_native_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(573, p, arg1, 0, 0, I);
}

Eterm
wrap_hibernate_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(574, p, arg1, arg2, arg3, I);
}

Eterm
wrap_error_logger_warning_map_0(Process* p, UWord *I)
{
    return erts_bif_trace(575, p, 0, 0, 0, I);
}

Eterm
wrap_get_module_info_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(576, p, arg1, 0, 0, I);
}

Eterm
wrap_get_module_info_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(577, p, arg1, arg2, 0, I);
}

Eterm
wrap_string_to_integer_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(579, p, arg1, 0, 0, I);
}

Eterm
wrap_string_to_float_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(580, p, arg1, 0, 0, I);
}

Eterm
wrap_make_fun_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(581, p, arg1, arg2, arg3, I);
}

Eterm
wrap_iolist_size_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(582, p, arg1, 0, 0, I);
}

Eterm
wrap_iolist_to_binary_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(583, p, arg1, 0, 0, I);
}

Eterm
wrap_list_to_existing_atom_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(584, p, arg1, 0, 0, I);
}

Eterm
wrap_list_to_bitstring_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(589, p, arg1, 0, 0, I);
}

Eterm
wrap_bitstring_to_list_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(590, p, arg1, 0, 0, I);
}

Eterm
wrap_ets_update_element_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(591, p, arg1, arg2, arg3, I);
}

Eterm
wrap_decode_packet_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(592, p, arg1, arg2, arg3, I);
}

Eterm
wrap_unicode_characters_to_binary_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(593, p, arg1, arg2, 0, I);
}

Eterm
wrap_unicode_characters_to_list_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(594, p, arg1, arg2, 0, I);
}

Eterm
wrap_unicode_bin_is_7bit_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(595, p, arg1, 0, 0, I);
}

Eterm
wrap_atom_to_binary_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(596, p, arg1, arg2, 0, I);
}

Eterm
wrap_binary_to_atom_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(597, p, arg1, arg2, 0, I);
}

Eterm
wrap_binary_to_existing_atom_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(598, p, arg1, arg2, 0, I);
}

Eterm
wrap_net_kernel_dflag_unicode_io_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(599, p, arg1, 0, 0, I);
}

Eterm
wrap_ets_give_away_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(600, p, arg1, arg2, arg3, I);
}

Eterm
wrap_ets_setopts_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(601, p, arg1, arg2, 0, I);
}

Eterm
wrap_load_nif_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(602, p, arg1, arg2, 0, I);
}

Eterm
wrap_call_on_load_function_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(603, p, arg1, 0, 0, I);
}

Eterm
wrap_finish_after_on_load_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(604, p, arg1, arg2, 0, I);
}

Eterm
wrap_binary_to_term_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(605, p, arg1, arg2, 0, I);
}

Eterm
wrap_binary_compile_pattern_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(608, p, arg1, 0, 0, I);
}

Eterm
wrap_binary_match_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(609, p, arg1, arg2, 0, I);
}

Eterm
wrap_binary_match_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(610, p, arg1, arg2, arg3, I);
}

Eterm
wrap_binary_matches_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(611, p, arg1, arg2, 0, I);
}

Eterm
wrap_binary_matches_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(612, p, arg1, arg2, arg3, I);
}

Eterm
wrap_binary_longest_common_prefix_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(613, p, arg1, 0, 0, I);
}

Eterm
wrap_binary_longest_common_suffix_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(614, p, arg1, 0, 0, I);
}

Eterm
wrap_binary_first_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(615, p, arg1, 0, 0, I);
}

Eterm
wrap_binary_last_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(616, p, arg1, 0, 0, I);
}

Eterm
wrap_binary_at_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(617, p, arg1, arg2, 0, I);
}

Eterm
wrap_binary_binary_part_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(618, p, arg1, arg2, 0, I);
}

Eterm
wrap_binary_binary_part_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(619, p, arg1, arg2, arg3, I);
}

Eterm
wrap_binary_bin_to_list_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(620, p, arg1, 0, 0, I);
}

Eterm
wrap_binary_bin_to_list_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(621, p, arg1, arg2, 0, I);
}

Eterm
wrap_binary_bin_to_list_3(Process* p, Eterm arg1, Eterm arg2, Eterm arg3, UWord *I)
{
    return erts_bif_trace(622, p, arg1, arg2, arg3, I);
}

Eterm
wrap_binary_list_to_bin_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(623, p, arg1, 0, 0, I);
}

Eterm
wrap_binary_copy_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(624, p, arg1, 0, 0, I);
}

Eterm
wrap_binary_copy_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(625, p, arg1, arg2, 0, I);
}

Eterm
wrap_binary_referenced_byte_size_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(626, p, arg1, 0, 0, I);
}

Eterm
wrap_binary_encode_unsigned_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(627, p, arg1, 0, 0, I);
}

Eterm
wrap_binary_encode_unsigned_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(628, p, arg1, arg2, 0, I);
}

Eterm
wrap_binary_decode_unsigned_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(629, p, arg1, 0, 0, I);
}

Eterm
wrap_binary_decode_unsigned_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(630, p, arg1, arg2, 0, I);
}

Eterm
wrap_nif_error_1(Process* p, Eterm arg1, UWord *I)
{
    return erts_bif_trace(631, p, arg1, 0, 0, I);
}

Eterm
wrap_nif_error_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(632, p, arg1, arg2, 0, I);
}

Eterm
wrap_hash_2(Process* p, Eterm arg1, Eterm arg2, UWord *I)
{
    return erts_bif_trace(633, p, arg1, arg2, 0, I);
}

